/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	

/* DO NOT EDIT - THIS FILE GENERATED BY THE tilesortspu_proto.py SCRIPT */

#ifndef TILESORT_SPU_PROTO_H
#define TILESORT_SPU_PROTO_H 1

#include <stdio.h>
#include "cr_string.h"
#include "cr_spu.h"
#include "tilesortspu.h"
#include "cr_packfunctions.h"
#include "cr_glstate.h"

extern void TILESORTSPU_APIENTRY tilesortspu_Accum( GLenum op, GLfloat value );
extern void TILESORTSPU_APIENTRY tilesortspu_ArrayElement( GLint i );
extern void TILESORTSPU_APIENTRY tilesortspu_BarrierCreateCR( GLuint name, GLuint count );
extern void TILESORTSPU_APIENTRY tilesortspu_BarrierDestroyCR( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_BarrierExecCR( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_Begin( GLenum mode );
extern void TILESORTSPU_APIENTRY tilesortspu_BeginQueryARB( GLenum target, GLuint id );
extern void TILESORTSPU_APIENTRY tilesortspu_Bitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap );
extern void TILESORTSPU_APIENTRY tilesortspu_BoundsInfoCR( const CRrecti * bounds, const GLbyte * payload, GLint len, GLint num_opcodes );
extern void TILESORTSPU_APIENTRY tilesortspu_BufferDataARB( GLenum target, GLsizeiptrARB size, const GLvoid * data, GLenum usage );
extern void TILESORTSPU_APIENTRY tilesortspu_BufferSubDataARB( GLenum target, GLintptrARB offset, GLsizeiptrARB size, const GLvoid * data );
extern void TILESORTSPU_APIENTRY tilesortspu_CallList( GLuint list );
extern void TILESORTSPU_APIENTRY tilesortspu_CallLists( GLsizei n, GLenum type, const GLvoid * lists );
extern void TILESORTSPU_APIENTRY tilesortspu_ChromiumParameterfCR( GLenum target, GLfloat value );
extern void TILESORTSPU_APIENTRY tilesortspu_ChromiumParameteriCR( GLenum target, GLint value );
extern void TILESORTSPU_APIENTRY tilesortspu_ChromiumParametervCR( GLenum target, GLenum type, GLsizei count, const GLvoid * values );
extern void TILESORTSPU_APIENTRY tilesortspu_Clear( GLbitfield mask );
extern void TILESORTSPU_APIENTRY tilesortspu_CopyPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum type );
extern void TILESORTSPU_APIENTRY tilesortspu_CopyTexImage1D( GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border );
extern void TILESORTSPU_APIENTRY tilesortspu_CopyTexImage2D( GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border );
extern void TILESORTSPU_APIENTRY tilesortspu_CopyTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width );
extern void TILESORTSPU_APIENTRY tilesortspu_CopyTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height );
extern void TILESORTSPU_APIENTRY tilesortspu_CopyTexSubImage3D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height );
extern GLint TILESORTSPU_APIENTRY tilesortspu_CreateContext( const char * dpyName, GLint visual );
extern void TILESORTSPU_APIENTRY tilesortspu_DeleteBuffersARB( GLsizei n, const GLuint * buffer );
extern void TILESORTSPU_APIENTRY tilesortspu_DeleteLists( GLuint list, GLsizei range );
extern void TILESORTSPU_APIENTRY tilesortspu_DeleteProgramsARB( GLsizei n, const GLuint * programs );
extern void TILESORTSPU_APIENTRY tilesortspu_DeleteTextures( GLsizei n, const GLuint * textures );
extern void TILESORTSPU_APIENTRY tilesortspu_DestroyContext( GLint ctx );
extern void TILESORTSPU_APIENTRY tilesortspu_DrawArrays( GLenum mode, GLint first, GLsizei count );
extern void TILESORTSPU_APIENTRY tilesortspu_DrawBuffer( GLenum mode );
extern void TILESORTSPU_APIENTRY tilesortspu_DrawElements( GLenum mode, GLsizei count, GLenum type, const GLvoid * indices );
extern void TILESORTSPU_APIENTRY tilesortspu_DrawPixels( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels );
extern void TILESORTSPU_APIENTRY tilesortspu_DrawRangeElements( GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices );
extern void TILESORTSPU_APIENTRY tilesortspu_End( void );
extern void TILESORTSPU_APIENTRY tilesortspu_EndList( void );
extern void TILESORTSPU_APIENTRY tilesortspu_EndQueryARB( GLenum target );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord1d( GLdouble u );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord1dv( const GLdouble * u );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord1f( GLfloat u );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord1fv( const GLfloat * u );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord2d( GLdouble u, GLdouble v );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord2dv( const GLdouble * u );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord2f( GLfloat u, GLfloat v );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalCoord2fv( const GLfloat * u );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalMesh1( GLenum mode, GLint i1, GLint i2 );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalMesh2( GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2 );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalPoint1( GLint i );
extern void TILESORTSPU_APIENTRY tilesortspu_EvalPoint2( GLint i, GLint j );
extern void TILESORTSPU_APIENTRY tilesortspu_FeedbackBuffer( GLsizei size, GLenum type, GLfloat * buffer );
extern void TILESORTSPU_APIENTRY tilesortspu_Finish( void );
extern void TILESORTSPU_APIENTRY tilesortspu_Flush( void );
extern GLuint TILESORTSPU_APIENTRY tilesortspu_GenLists( GLsizei range );
extern void TILESORTSPU_APIENTRY tilesortspu_GetBooleanv( GLenum pname, GLboolean * params );
extern void TILESORTSPU_APIENTRY tilesortspu_GetBufferSubDataARB( GLenum target, GLintptrARB offset, GLsizeiptrARB size, void * data );
extern void TILESORTSPU_APIENTRY tilesortspu_GetChromiumParametervCR( GLenum target, GLuint index, GLenum type, GLsizei count, GLvoid * values );
extern void TILESORTSPU_APIENTRY tilesortspu_GetDoublev( GLenum pname, GLdouble * params );
extern void TILESORTSPU_APIENTRY tilesortspu_GetFloatv( GLenum pname, GLfloat * params );
extern void TILESORTSPU_APIENTRY tilesortspu_GetIntegerv( GLenum pname, GLint * params );
extern void TILESORTSPU_APIENTRY tilesortspu_GetQueryObjectivARB( GLuint id, GLenum pname, GLint * params );
extern void TILESORTSPU_APIENTRY tilesortspu_GetQueryObjectuivARB( GLuint id, GLenum pname, GLuint * params );
extern const GLubyte * TILESORTSPU_APIENTRY tilesortspu_GetString( GLenum name );
extern void TILESORTSPU_APIENTRY tilesortspu_InitNames( void );
extern void TILESORTSPU_APIENTRY tilesortspu_ListBase( GLuint base );
extern void TILESORTSPU_APIENTRY tilesortspu_LoadName( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_MakeCurrent( GLint window, GLint nativeWindow, GLint ctx );
extern void * TILESORTSPU_APIENTRY tilesortspu_MapBufferARB( GLenum target, GLenum access );
extern void TILESORTSPU_APIENTRY tilesortspu_Materialf( GLenum face, GLenum pname, GLfloat param );
extern void TILESORTSPU_APIENTRY tilesortspu_Materialfv( GLenum face, GLenum pname, const GLfloat * params );
extern void TILESORTSPU_APIENTRY tilesortspu_Materiali( GLenum face, GLenum pname, GLint param );
extern void TILESORTSPU_APIENTRY tilesortspu_Materialiv( GLenum face, GLenum pname, const GLint * params );
extern void TILESORTSPU_APIENTRY tilesortspu_MultiDrawArraysEXT( GLenum mode, GLint * first, GLsizei * count, GLsizei primcount );
extern void TILESORTSPU_APIENTRY tilesortspu_MultiDrawElementsEXT( GLenum mode, const GLsizei * count, GLenum type, const GLvoid ** indices, GLsizei primcount );
extern void TILESORTSPU_APIENTRY tilesortspu_NewList( GLuint list, GLenum mode );
extern void TILESORTSPU_APIENTRY tilesortspu_PassThrough( GLfloat token );
extern void TILESORTSPU_APIENTRY tilesortspu_PixelMapfv( GLenum map, GLsizei mapsize, const GLfloat * values );
extern void TILESORTSPU_APIENTRY tilesortspu_PixelMapuiv( GLenum map, GLsizei mapsize, const GLuint * values );
extern void TILESORTSPU_APIENTRY tilesortspu_PixelMapusv( GLenum map, GLsizei mapsize, const GLushort * values );
extern void TILESORTSPU_APIENTRY tilesortspu_PixelTransferf( GLenum pname, GLfloat param );
extern void TILESORTSPU_APIENTRY tilesortspu_PixelTransferi( GLenum pname, GLint param );
extern void TILESORTSPU_APIENTRY tilesortspu_PopAttrib( void );
extern void TILESORTSPU_APIENTRY tilesortspu_PopName( void );
extern void TILESORTSPU_APIENTRY tilesortspu_PushName( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2d( GLdouble x, GLdouble y );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2dv( const GLdouble * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2f( GLfloat x, GLfloat y );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2fv( const GLfloat * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2i( GLint x, GLint y );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2iv( const GLint * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2s( GLshort x, GLshort y );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos2sv( const GLshort * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3d( GLdouble x, GLdouble y, GLdouble z );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3dv( const GLdouble * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3f( GLfloat x, GLfloat y, GLfloat z );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3fv( const GLfloat * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3i( GLint x, GLint y, GLint z );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3iv( const GLint * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3s( GLshort x, GLshort y, GLshort z );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos3sv( const GLshort * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4dv( const GLdouble * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4fv( const GLfloat * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4i( GLint x, GLint y, GLint z, GLint w );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4iv( const GLint * v );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4s( GLshort x, GLshort y, GLshort z, GLshort w );
extern void TILESORTSPU_APIENTRY tilesortspu_RasterPos4sv( const GLshort * v );
extern void TILESORTSPU_APIENTRY tilesortspu_ReadPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels );
extern void TILESORTSPU_APIENTRY tilesortspu_Rectd( GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Rectdv( const GLdouble * v1, const GLdouble * v2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Rectf( GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Rectfv( const GLfloat * v1, const GLfloat * v2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Recti( GLint x1, GLint y1, GLint x2, GLint y2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Rectiv( const GLint * v1, const GLint * v2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Rects( GLshort x1, GLshort y1, GLshort x2, GLshort y2 );
extern void TILESORTSPU_APIENTRY tilesortspu_Rectsv( const GLshort * v1, const GLshort * v2 );
extern GLint TILESORTSPU_APIENTRY tilesortspu_RenderMode( GLenum mode );
extern void TILESORTSPU_APIENTRY tilesortspu_Scissor( GLint x, GLint y, GLsizei width, GLsizei height );
extern void TILESORTSPU_APIENTRY tilesortspu_SelectBuffer( GLsizei size, GLuint * buffer );
extern void TILESORTSPU_APIENTRY tilesortspu_SemaphoreCreateCR( GLuint name, GLuint count );
extern void TILESORTSPU_APIENTRY tilesortspu_SemaphoreDestroyCR( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_SemaphorePCR( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_SemaphoreVCR( GLuint name );
extern void TILESORTSPU_APIENTRY tilesortspu_SwapBuffers( GLint window, GLint flags );
extern GLboolean TILESORTSPU_APIENTRY tilesortspu_UnmapBufferARB( GLenum target );
extern void TILESORTSPU_APIENTRY tilesortspu_Viewport( GLint x, GLint y, GLsizei width, GLsizei height );
extern GLint TILESORTSPU_APIENTRY tilesortspu_WindowCreate( const char * dpyName, GLint visBits );
extern void TILESORTSPU_APIENTRY tilesortspu_WindowDestroy( GLint window );
extern void TILESORTSPU_APIENTRY tilesortspu_WindowPosition( GLint window, GLint x, GLint y );
extern void TILESORTSPU_APIENTRY tilesortspu_WindowSize( GLint window, GLint w, GLint h );
extern void TILESORTSPU_APIENTRY tilesortspu_ZPixCR( GLsizei width, GLsizei height, GLenum format, GLenum type, GLenum ztype, GLint zparm, GLint length, const GLvoid * pixels );

#endif

