/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	

/* DO NOT EDIT - THIS FILE GENERATED BY THE diffapi.py SCRIPT */
#include "cr_spu.h"
#include "cr_packfunctions.h"
#include "replicatespu.h"
#include "replicatespu_proto.h"

#include <stdio.h>

static const CRPixelPackState defaultPacking = {
	0, 		/* rowLength */
	0, 		/* skipRows */
	0, 		/* skipPixels */
	1, 		/* alignment */
	0, 		/* imageHeight */
	0, 		/* skipImages */
	GL_FALSE, 	/* swapBytes */
	GL_FALSE  	/* psLSBFirst */
};


extern void REPLICATESPU_APIENTRY replicatespu_DiffBitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap );
extern void REPLICATESPU_APIENTRY replicatespu_DiffDrawPixels( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexImage1D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexImage2D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexImage3D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexImage3DEXT( GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffTexSubImage3D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels );
extern void REPLICATESPU_APIENTRY replicatespu_DiffZPixCR( GLsizei width, GLsizei height, GLenum format, GLenum type, GLenum ztype, GLint zparm, GLint length, const GLvoid * pixels );
void REPLICATESPU_APIENTRY replicatespu_DiffBitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap )
{
	if (replicate_spu.swap)
	{
		crPackBitmapSWAP( width, height, xorig, yorig, xmove, ymove, bitmap, &defaultPacking );
	}
	else
	{
		crPackBitmap( width, height, xorig, yorig, xmove, ymove, bitmap, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffDrawPixels( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackDrawPixelsSWAP( width, height, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackDrawPixels( width, height, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexImage1D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexImage1DSWAP( target, level, internalFormat, width, border, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexImage1D( target, level, internalFormat, width, border, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexImage2D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexImage2DSWAP( target, level, internalFormat, width, height, border, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexImage2D( target, level, internalFormat, width, height, border, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexImage3D( GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexImage3DSWAP( target, level, internalFormat, width, height, depth, border, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexImage3D( target, level, internalFormat, width, height, depth, border, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexImage3DEXT( GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexImage3DEXTSWAP( target, level, internalFormat, width, height, depth, border, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexImage3DEXT( target, level, internalFormat, width, height, depth, border, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexSubImage1DSWAP( target, level, xoffset, width, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexSubImage1D( target, level, xoffset, width, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexSubImage2DSWAP( target, level, xoffset, yoffset, width, height, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexSubImage2D( target, level, xoffset, yoffset, width, height, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffTexSubImage3D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackTexSubImage3DSWAP( target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels, &defaultPacking );
	}
	else
	{
		crPackTexSubImage3D( target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels, &defaultPacking );
	}
}
void REPLICATESPU_APIENTRY replicatespu_DiffZPixCR( GLsizei width, GLsizei height, GLenum format, GLenum type, GLenum ztype, GLint zparm, GLint length, const GLvoid * pixels )
{
	if (replicate_spu.swap)
	{
		crPackZPixCRSWAP( width, height, format, type, ztype, zparm, length, pixels, &defaultPacking );
	}
	else
	{
		crPackZPixCR( width, height, format, type, ztype, zparm, length, pixels, &defaultPacking );
	}
}

void replicatespuCreateDiffAPI( void )
{

	replicate_spu.diff_dispatch.Accum = (replicate_spu.swap ? crPackAccumSWAP : crPackAccum);
	replicate_spu.diff_dispatch.ActiveTextureARB = (replicate_spu.swap ? crPackActiveTextureARBSWAP : crPackActiveTextureARB);
	replicate_spu.diff_dispatch.AlphaFunc = (replicate_spu.swap ? crPackAlphaFuncSWAP : crPackAlphaFunc);
	replicate_spu.diff_dispatch.AreProgramsResidentNV = NULL;
	replicate_spu.diff_dispatch.AreTexturesResident = NULL;
	replicate_spu.diff_dispatch.ArrayElement = (replicate_spu.swap ? crPackArrayElementSWAP : crPackArrayElement);
	replicate_spu.diff_dispatch.BarrierCreateCR = (replicate_spu.swap ? crPackBarrierCreateCRSWAP : crPackBarrierCreateCR);
	replicate_spu.diff_dispatch.BarrierDestroyCR = (replicate_spu.swap ? crPackBarrierDestroyCRSWAP : crPackBarrierDestroyCR);
	replicate_spu.diff_dispatch.BarrierExecCR = (replicate_spu.swap ? crPackBarrierExecCRSWAP : crPackBarrierExecCR);
	replicate_spu.diff_dispatch.Begin = (replicate_spu.swap ? crPackBeginSWAP : crPackBegin);
	replicate_spu.diff_dispatch.BeginQueryARB = (replicate_spu.swap ? crPackBeginQueryARBSWAP : crPackBeginQueryARB);
	replicate_spu.diff_dispatch.BindBufferARB = (replicate_spu.swap ? crPackBindBufferARBSWAP : crPackBindBufferARB);
	replicate_spu.diff_dispatch.BindProgramARB = (replicate_spu.swap ? crPackBindProgramARBSWAP : crPackBindProgramARB);
	replicate_spu.diff_dispatch.BindProgramNV = (replicate_spu.swap ? crPackBindProgramNVSWAP : crPackBindProgramNV);
	replicate_spu.diff_dispatch.BindTexture = (replicate_spu.swap ? crPackBindTextureSWAP : crPackBindTexture);
	replicate_spu.diff_dispatch.Bitmap = replicatespu_DiffBitmap;
	replicate_spu.diff_dispatch.BlendColorEXT = (replicate_spu.swap ? crPackBlendColorEXTSWAP : crPackBlendColorEXT);
	replicate_spu.diff_dispatch.BlendEquationEXT = (replicate_spu.swap ? crPackBlendEquationEXTSWAP : crPackBlendEquationEXT);
	replicate_spu.diff_dispatch.BlendFunc = (replicate_spu.swap ? crPackBlendFuncSWAP : crPackBlendFunc);
	replicate_spu.diff_dispatch.BlendFuncSeparateEXT = (replicate_spu.swap ? crPackBlendFuncSeparateEXTSWAP : crPackBlendFuncSeparateEXT);
	replicate_spu.diff_dispatch.BoundsInfoCR = (replicate_spu.swap ? crPackBoundsInfoCRSWAP : crPackBoundsInfoCR);
	replicate_spu.diff_dispatch.BufferDataARB = (replicate_spu.swap ? crPackBufferDataARBSWAP : crPackBufferDataARB);
	replicate_spu.diff_dispatch.BufferSubDataARB = (replicate_spu.swap ? crPackBufferSubDataARBSWAP : crPackBufferSubDataARB);
	replicate_spu.diff_dispatch.CallList = (replicate_spu.swap ? crPackCallListSWAP : crPackCallList);
	replicate_spu.diff_dispatch.CallLists = (replicate_spu.swap ? crPackCallListsSWAP : crPackCallLists);
	replicate_spu.diff_dispatch.ChromiumParameterfCR = (replicate_spu.swap ? crPackChromiumParameterfCRSWAP : crPackChromiumParameterfCR);
	replicate_spu.diff_dispatch.ChromiumParameteriCR = (replicate_spu.swap ? crPackChromiumParameteriCRSWAP : crPackChromiumParameteriCR);
	replicate_spu.diff_dispatch.ChromiumParametervCR = (replicate_spu.swap ? crPackChromiumParametervCRSWAP : crPackChromiumParametervCR);
	replicate_spu.diff_dispatch.Clear = (replicate_spu.swap ? crPackClearSWAP : crPackClear);
	replicate_spu.diff_dispatch.ClearAccum = (replicate_spu.swap ? crPackClearAccumSWAP : crPackClearAccum);
	replicate_spu.diff_dispatch.ClearColor = (replicate_spu.swap ? crPackClearColorSWAP : crPackClearColor);
	replicate_spu.diff_dispatch.ClearDepth = (replicate_spu.swap ? crPackClearDepthSWAP : crPackClearDepth);
	replicate_spu.diff_dispatch.ClearIndex = (replicate_spu.swap ? crPackClearIndexSWAP : crPackClearIndex);
	replicate_spu.diff_dispatch.ClearStencil = (replicate_spu.swap ? crPackClearStencilSWAP : crPackClearStencil);
	replicate_spu.diff_dispatch.ClientActiveTextureARB = (replicate_spu.swap ? crPackClientActiveTextureARBSWAP : crPackClientActiveTextureARB);
	replicate_spu.diff_dispatch.ClipPlane = (replicate_spu.swap ? crPackClipPlaneSWAP : crPackClipPlane);
	replicate_spu.diff_dispatch.Color3b = (replicate_spu.swap ? crPackColor3bSWAP : crPackColor3b);
	replicate_spu.diff_dispatch.Color3bv = (replicate_spu.swap ? crPackColor3bvSWAP : crPackColor3bv);
	replicate_spu.diff_dispatch.Color3d = (replicate_spu.swap ? crPackColor3dSWAP : crPackColor3d);
	replicate_spu.diff_dispatch.Color3dv = (replicate_spu.swap ? crPackColor3dvSWAP : crPackColor3dv);
	replicate_spu.diff_dispatch.Color3f = (replicate_spu.swap ? crPackColor3fSWAP : crPackColor3f);
	replicate_spu.diff_dispatch.Color3fv = (replicate_spu.swap ? crPackColor3fvSWAP : crPackColor3fv);
	replicate_spu.diff_dispatch.Color3i = (replicate_spu.swap ? crPackColor3iSWAP : crPackColor3i);
	replicate_spu.diff_dispatch.Color3iv = (replicate_spu.swap ? crPackColor3ivSWAP : crPackColor3iv);
	replicate_spu.diff_dispatch.Color3s = (replicate_spu.swap ? crPackColor3sSWAP : crPackColor3s);
	replicate_spu.diff_dispatch.Color3sv = (replicate_spu.swap ? crPackColor3svSWAP : crPackColor3sv);
	replicate_spu.diff_dispatch.Color3ub = (replicate_spu.swap ? crPackColor3ubSWAP : crPackColor3ub);
	replicate_spu.diff_dispatch.Color3ubv = (replicate_spu.swap ? crPackColor3ubvSWAP : crPackColor3ubv);
	replicate_spu.diff_dispatch.Color3ui = (replicate_spu.swap ? crPackColor3uiSWAP : crPackColor3ui);
	replicate_spu.diff_dispatch.Color3uiv = (replicate_spu.swap ? crPackColor3uivSWAP : crPackColor3uiv);
	replicate_spu.diff_dispatch.Color3us = (replicate_spu.swap ? crPackColor3usSWAP : crPackColor3us);
	replicate_spu.diff_dispatch.Color3usv = (replicate_spu.swap ? crPackColor3usvSWAP : crPackColor3usv);
	replicate_spu.diff_dispatch.Color4b = (replicate_spu.swap ? crPackColor4bSWAP : crPackColor4b);
	replicate_spu.diff_dispatch.Color4bv = (replicate_spu.swap ? crPackColor4bvSWAP : crPackColor4bv);
	replicate_spu.diff_dispatch.Color4d = (replicate_spu.swap ? crPackColor4dSWAP : crPackColor4d);
	replicate_spu.diff_dispatch.Color4dv = (replicate_spu.swap ? crPackColor4dvSWAP : crPackColor4dv);
	replicate_spu.diff_dispatch.Color4f = (replicate_spu.swap ? crPackColor4fSWAP : crPackColor4f);
	replicate_spu.diff_dispatch.Color4fv = (replicate_spu.swap ? crPackColor4fvSWAP : crPackColor4fv);
	replicate_spu.diff_dispatch.Color4i = (replicate_spu.swap ? crPackColor4iSWAP : crPackColor4i);
	replicate_spu.diff_dispatch.Color4iv = (replicate_spu.swap ? crPackColor4ivSWAP : crPackColor4iv);
	replicate_spu.diff_dispatch.Color4s = (replicate_spu.swap ? crPackColor4sSWAP : crPackColor4s);
	replicate_spu.diff_dispatch.Color4sv = (replicate_spu.swap ? crPackColor4svSWAP : crPackColor4sv);
	replicate_spu.diff_dispatch.Color4ub = (replicate_spu.swap ? crPackColor4ubSWAP : crPackColor4ub);
	replicate_spu.diff_dispatch.Color4ubv = (replicate_spu.swap ? crPackColor4ubvSWAP : crPackColor4ubv);
	replicate_spu.diff_dispatch.Color4ui = (replicate_spu.swap ? crPackColor4uiSWAP : crPackColor4ui);
	replicate_spu.diff_dispatch.Color4uiv = (replicate_spu.swap ? crPackColor4uivSWAP : crPackColor4uiv);
	replicate_spu.diff_dispatch.Color4us = (replicate_spu.swap ? crPackColor4usSWAP : crPackColor4us);
	replicate_spu.diff_dispatch.Color4usv = (replicate_spu.swap ? crPackColor4usvSWAP : crPackColor4usv);
	replicate_spu.diff_dispatch.ColorMask = (replicate_spu.swap ? crPackColorMaskSWAP : crPackColorMask);
	replicate_spu.diff_dispatch.ColorMaterial = (replicate_spu.swap ? crPackColorMaterialSWAP : crPackColorMaterial);
	replicate_spu.diff_dispatch.ColorPointer = (replicate_spu.swap ? crPackColorPointerSWAP : crPackColorPointer);
	replicate_spu.diff_dispatch.CombinerInputNV = (replicate_spu.swap ? crPackCombinerInputNVSWAP : crPackCombinerInputNV);
	replicate_spu.diff_dispatch.CombinerOutputNV = (replicate_spu.swap ? crPackCombinerOutputNVSWAP : crPackCombinerOutputNV);
	replicate_spu.diff_dispatch.CombinerParameterfNV = (replicate_spu.swap ? crPackCombinerParameterfNVSWAP : crPackCombinerParameterfNV);
	replicate_spu.diff_dispatch.CombinerParameterfvNV = (replicate_spu.swap ? crPackCombinerParameterfvNVSWAP : crPackCombinerParameterfvNV);
	replicate_spu.diff_dispatch.CombinerParameteriNV = (replicate_spu.swap ? crPackCombinerParameteriNVSWAP : crPackCombinerParameteriNV);
	replicate_spu.diff_dispatch.CombinerParameterivNV = (replicate_spu.swap ? crPackCombinerParameterivNVSWAP : crPackCombinerParameterivNV);
	replicate_spu.diff_dispatch.CombinerStageParameterfvNV = (replicate_spu.swap ? crPackCombinerStageParameterfvNVSWAP : crPackCombinerStageParameterfvNV);
	replicate_spu.diff_dispatch.CompressedTexImage1DARB = (replicate_spu.swap ? crPackCompressedTexImage1DARBSWAP : crPackCompressedTexImage1DARB);
	replicate_spu.diff_dispatch.CompressedTexImage2DARB = (replicate_spu.swap ? crPackCompressedTexImage2DARBSWAP : crPackCompressedTexImage2DARB);
	replicate_spu.diff_dispatch.CompressedTexImage3DARB = (replicate_spu.swap ? crPackCompressedTexImage3DARBSWAP : crPackCompressedTexImage3DARB);
	replicate_spu.diff_dispatch.CompressedTexSubImage1DARB = (replicate_spu.swap ? crPackCompressedTexSubImage1DARBSWAP : crPackCompressedTexSubImage1DARB);
	replicate_spu.diff_dispatch.CompressedTexSubImage2DARB = (replicate_spu.swap ? crPackCompressedTexSubImage2DARBSWAP : crPackCompressedTexSubImage2DARB);
	replicate_spu.diff_dispatch.CompressedTexSubImage3DARB = (replicate_spu.swap ? crPackCompressedTexSubImage3DARBSWAP : crPackCompressedTexSubImage3DARB);
	replicate_spu.diff_dispatch.CopyPixels = (replicate_spu.swap ? crPackCopyPixelsSWAP : crPackCopyPixels);
	replicate_spu.diff_dispatch.CopyTexImage1D = (replicate_spu.swap ? crPackCopyTexImage1DSWAP : crPackCopyTexImage1D);
	replicate_spu.diff_dispatch.CopyTexImage2D = (replicate_spu.swap ? crPackCopyTexImage2DSWAP : crPackCopyTexImage2D);
	replicate_spu.diff_dispatch.CopyTexSubImage1D = (replicate_spu.swap ? crPackCopyTexSubImage1DSWAP : crPackCopyTexSubImage1D);
	replicate_spu.diff_dispatch.CopyTexSubImage2D = (replicate_spu.swap ? crPackCopyTexSubImage2DSWAP : crPackCopyTexSubImage2D);
	replicate_spu.diff_dispatch.CopyTexSubImage3D = (replicate_spu.swap ? crPackCopyTexSubImage3DSWAP : crPackCopyTexSubImage3D);
	replicate_spu.diff_dispatch.CreateContext = NULL;
	replicate_spu.diff_dispatch.CullFace = (replicate_spu.swap ? crPackCullFaceSWAP : crPackCullFace);
	replicate_spu.diff_dispatch.DeleteBuffersARB = (replicate_spu.swap ? crPackDeleteBuffersARBSWAP : crPackDeleteBuffersARB);
	replicate_spu.diff_dispatch.DeleteFencesNV = (replicate_spu.swap ? crPackDeleteFencesNVSWAP : crPackDeleteFencesNV);
	replicate_spu.diff_dispatch.DeleteLists = (replicate_spu.swap ? crPackDeleteListsSWAP : crPackDeleteLists);
	replicate_spu.diff_dispatch.DeleteProgramsARB = (replicate_spu.swap ? crPackDeleteProgramsARBSWAP : crPackDeleteProgramsARB);
	replicate_spu.diff_dispatch.DeleteQueriesARB = (replicate_spu.swap ? crPackDeleteQueriesARBSWAP : crPackDeleteQueriesARB);
	replicate_spu.diff_dispatch.DeleteTextures = (replicate_spu.swap ? crPackDeleteTexturesSWAP : crPackDeleteTextures);
	replicate_spu.diff_dispatch.DepthFunc = (replicate_spu.swap ? crPackDepthFuncSWAP : crPackDepthFunc);
	replicate_spu.diff_dispatch.DepthMask = (replicate_spu.swap ? crPackDepthMaskSWAP : crPackDepthMask);
	replicate_spu.diff_dispatch.DepthRange = (replicate_spu.swap ? crPackDepthRangeSWAP : crPackDepthRange);
	replicate_spu.diff_dispatch.DestroyContext = (replicate_spu.swap ? crPackDestroyContextSWAP : crPackDestroyContext);
	replicate_spu.diff_dispatch.Disable = (replicate_spu.swap ? crPackDisableSWAP : crPackDisable);
	replicate_spu.diff_dispatch.DisableClientState = (replicate_spu.swap ? crPackDisableClientStateSWAP : crPackDisableClientState);
	replicate_spu.diff_dispatch.DisableVertexAttribArrayARB = (replicate_spu.swap ? crPackDisableVertexAttribArrayARBSWAP : crPackDisableVertexAttribArrayARB);
	replicate_spu.diff_dispatch.DrawArrays = (replicate_spu.swap ? crPackDrawArraysSWAP : crPackDrawArrays);
	replicate_spu.diff_dispatch.DrawBuffer = (replicate_spu.swap ? crPackDrawBufferSWAP : crPackDrawBuffer);
	replicate_spu.diff_dispatch.DrawElements = (replicate_spu.swap ? crPackDrawElementsSWAP : crPackDrawElements);
	replicate_spu.diff_dispatch.DrawPixels = replicatespu_DiffDrawPixels;
	replicate_spu.diff_dispatch.DrawRangeElements = (replicate_spu.swap ? crPackDrawRangeElementsSWAP : crPackDrawRangeElements);
	replicate_spu.diff_dispatch.EdgeFlag = (replicate_spu.swap ? crPackEdgeFlagSWAP : crPackEdgeFlag);
	replicate_spu.diff_dispatch.EdgeFlagPointer = (replicate_spu.swap ? crPackEdgeFlagPointerSWAP : crPackEdgeFlagPointer);
	replicate_spu.diff_dispatch.EdgeFlagv = (replicate_spu.swap ? crPackEdgeFlagvSWAP : crPackEdgeFlagv);
	replicate_spu.diff_dispatch.Enable = (replicate_spu.swap ? crPackEnableSWAP : crPackEnable);
	replicate_spu.diff_dispatch.EnableClientState = (replicate_spu.swap ? crPackEnableClientStateSWAP : crPackEnableClientState);
	replicate_spu.diff_dispatch.EnableVertexAttribArrayARB = (replicate_spu.swap ? crPackEnableVertexAttribArrayARBSWAP : crPackEnableVertexAttribArrayARB);
	replicate_spu.diff_dispatch.End = (replicate_spu.swap ? crPackEndSWAP : crPackEnd);
	replicate_spu.diff_dispatch.EndList = (replicate_spu.swap ? crPackEndListSWAP : crPackEndList);
	replicate_spu.diff_dispatch.EndQueryARB = (replicate_spu.swap ? crPackEndQueryARBSWAP : crPackEndQueryARB);
	replicate_spu.diff_dispatch.EvalCoord1d = (replicate_spu.swap ? crPackEvalCoord1dSWAP : crPackEvalCoord1d);
	replicate_spu.diff_dispatch.EvalCoord1dv = (replicate_spu.swap ? crPackEvalCoord1dvSWAP : crPackEvalCoord1dv);
	replicate_spu.diff_dispatch.EvalCoord1f = (replicate_spu.swap ? crPackEvalCoord1fSWAP : crPackEvalCoord1f);
	replicate_spu.diff_dispatch.EvalCoord1fv = (replicate_spu.swap ? crPackEvalCoord1fvSWAP : crPackEvalCoord1fv);
	replicate_spu.diff_dispatch.EvalCoord2d = (replicate_spu.swap ? crPackEvalCoord2dSWAP : crPackEvalCoord2d);
	replicate_spu.diff_dispatch.EvalCoord2dv = (replicate_spu.swap ? crPackEvalCoord2dvSWAP : crPackEvalCoord2dv);
	replicate_spu.diff_dispatch.EvalCoord2f = (replicate_spu.swap ? crPackEvalCoord2fSWAP : crPackEvalCoord2f);
	replicate_spu.diff_dispatch.EvalCoord2fv = (replicate_spu.swap ? crPackEvalCoord2fvSWAP : crPackEvalCoord2fv);
	replicate_spu.diff_dispatch.EvalMesh1 = (replicate_spu.swap ? crPackEvalMesh1SWAP : crPackEvalMesh1);
	replicate_spu.diff_dispatch.EvalMesh2 = (replicate_spu.swap ? crPackEvalMesh2SWAP : crPackEvalMesh2);
	replicate_spu.diff_dispatch.EvalPoint1 = (replicate_spu.swap ? crPackEvalPoint1SWAP : crPackEvalPoint1);
	replicate_spu.diff_dispatch.EvalPoint2 = (replicate_spu.swap ? crPackEvalPoint2SWAP : crPackEvalPoint2);
	replicate_spu.diff_dispatch.ExecuteProgramNV = (replicate_spu.swap ? crPackExecuteProgramNVSWAP : crPackExecuteProgramNV);
	replicate_spu.diff_dispatch.FeedbackBuffer = (replicate_spu.swap ? crPackFeedbackBufferSWAP : crPackFeedbackBuffer);
	replicate_spu.diff_dispatch.FinalCombinerInputNV = (replicate_spu.swap ? crPackFinalCombinerInputNVSWAP : crPackFinalCombinerInputNV);
	replicate_spu.diff_dispatch.Finish = (replicate_spu.swap ? crPackFinishSWAP : crPackFinish);
	replicate_spu.diff_dispatch.FinishFenceNV = (replicate_spu.swap ? crPackFinishFenceNVSWAP : crPackFinishFenceNV);
	replicate_spu.diff_dispatch.Flush = (replicate_spu.swap ? crPackFlushSWAP : crPackFlush);
	replicate_spu.diff_dispatch.FlushVertexArrayRangeNV = (replicate_spu.swap ? crPackFlushVertexArrayRangeNVSWAP : crPackFlushVertexArrayRangeNV);
	replicate_spu.diff_dispatch.FogCoordPointerEXT = (replicate_spu.swap ? crPackFogCoordPointerEXTSWAP : crPackFogCoordPointerEXT);
	replicate_spu.diff_dispatch.FogCoorddEXT = (replicate_spu.swap ? crPackFogCoorddEXTSWAP : crPackFogCoorddEXT);
	replicate_spu.diff_dispatch.FogCoorddvEXT = (replicate_spu.swap ? crPackFogCoorddvEXTSWAP : crPackFogCoorddvEXT);
	replicate_spu.diff_dispatch.FogCoordfEXT = (replicate_spu.swap ? crPackFogCoordfEXTSWAP : crPackFogCoordfEXT);
	replicate_spu.diff_dispatch.FogCoordfvEXT = (replicate_spu.swap ? crPackFogCoordfvEXTSWAP : crPackFogCoordfvEXT);
	replicate_spu.diff_dispatch.Fogf = (replicate_spu.swap ? crPackFogfSWAP : crPackFogf);
	replicate_spu.diff_dispatch.Fogfv = (replicate_spu.swap ? crPackFogfvSWAP : crPackFogfv);
	replicate_spu.diff_dispatch.Fogi = (replicate_spu.swap ? crPackFogiSWAP : crPackFogi);
	replicate_spu.diff_dispatch.Fogiv = (replicate_spu.swap ? crPackFogivSWAP : crPackFogiv);
	replicate_spu.diff_dispatch.FrontFace = (replicate_spu.swap ? crPackFrontFaceSWAP : crPackFrontFace);
	replicate_spu.diff_dispatch.Frustum = (replicate_spu.swap ? crPackFrustumSWAP : crPackFrustum);
	replicate_spu.diff_dispatch.GenBuffersARB = NULL;
	replicate_spu.diff_dispatch.GenFencesNV = NULL;
	replicate_spu.diff_dispatch.GenLists = NULL;
	replicate_spu.diff_dispatch.GenProgramsARB = NULL;
	replicate_spu.diff_dispatch.GenProgramsNV = NULL;
	replicate_spu.diff_dispatch.GenQueriesARB = NULL;
	replicate_spu.diff_dispatch.GenTextures = NULL;
	replicate_spu.diff_dispatch.GetBooleanv = NULL;
	replicate_spu.diff_dispatch.GetBufferParameterivARB = NULL;
	replicate_spu.diff_dispatch.GetBufferPointervARB = NULL;
	replicate_spu.diff_dispatch.GetBufferSubDataARB = NULL;
	replicate_spu.diff_dispatch.GetChromiumParametervCR = NULL;
	replicate_spu.diff_dispatch.GetClipPlane = NULL;
	replicate_spu.diff_dispatch.GetCombinerInputParameterfvNV = NULL;
	replicate_spu.diff_dispatch.GetCombinerInputParameterivNV = NULL;
	replicate_spu.diff_dispatch.GetCombinerOutputParameterfvNV = NULL;
	replicate_spu.diff_dispatch.GetCombinerOutputParameterivNV = NULL;
	replicate_spu.diff_dispatch.GetCombinerStageParameterfvNV = NULL;
	replicate_spu.diff_dispatch.GetCompressedTexImageARB = NULL;
	replicate_spu.diff_dispatch.GetDoublev = NULL;
	replicate_spu.diff_dispatch.GetError = NULL;
	replicate_spu.diff_dispatch.GetFenceivNV = NULL;
	replicate_spu.diff_dispatch.GetFinalCombinerInputParameterfvNV = NULL;
	replicate_spu.diff_dispatch.GetFinalCombinerInputParameterivNV = NULL;
	replicate_spu.diff_dispatch.GetFloatv = NULL;
	replicate_spu.diff_dispatch.GetIntegerv = NULL;
	replicate_spu.diff_dispatch.GetLightfv = NULL;
	replicate_spu.diff_dispatch.GetLightiv = NULL;
	replicate_spu.diff_dispatch.GetMapdv = NULL;
	replicate_spu.diff_dispatch.GetMapfv = NULL;
	replicate_spu.diff_dispatch.GetMapiv = NULL;
	replicate_spu.diff_dispatch.GetMaterialfv = NULL;
	replicate_spu.diff_dispatch.GetMaterialiv = NULL;
	replicate_spu.diff_dispatch.GetPixelMapfv = NULL;
	replicate_spu.diff_dispatch.GetPixelMapuiv = NULL;
	replicate_spu.diff_dispatch.GetPixelMapusv = NULL;
	replicate_spu.diff_dispatch.GetPointerv = NULL;
	replicate_spu.diff_dispatch.GetPolygonStipple = NULL;
	replicate_spu.diff_dispatch.GetProgramEnvParameterdvARB = NULL;
	replicate_spu.diff_dispatch.GetProgramEnvParameterfvARB = NULL;
	replicate_spu.diff_dispatch.GetProgramLocalParameterdvARB = NULL;
	replicate_spu.diff_dispatch.GetProgramLocalParameterfvARB = NULL;
	replicate_spu.diff_dispatch.GetProgramNamedParameterdvNV = NULL;
	replicate_spu.diff_dispatch.GetProgramNamedParameterfvNV = NULL;
	replicate_spu.diff_dispatch.GetProgramParameterdvNV = NULL;
	replicate_spu.diff_dispatch.GetProgramParameterfvNV = NULL;
	replicate_spu.diff_dispatch.GetProgramStringARB = NULL;
	replicate_spu.diff_dispatch.GetProgramStringNV = NULL;
	replicate_spu.diff_dispatch.GetProgramivARB = NULL;
	replicate_spu.diff_dispatch.GetProgramivNV = NULL;
	replicate_spu.diff_dispatch.GetQueryObjectivARB = NULL;
	replicate_spu.diff_dispatch.GetQueryObjectuivARB = NULL;
	replicate_spu.diff_dispatch.GetQueryivARB = NULL;
	replicate_spu.diff_dispatch.GetString = NULL;
	replicate_spu.diff_dispatch.GetTexEnvfv = NULL;
	replicate_spu.diff_dispatch.GetTexEnviv = NULL;
	replicate_spu.diff_dispatch.GetTexGendv = NULL;
	replicate_spu.diff_dispatch.GetTexGenfv = NULL;
	replicate_spu.diff_dispatch.GetTexGeniv = NULL;
	replicate_spu.diff_dispatch.GetTexImage = NULL;
	replicate_spu.diff_dispatch.GetTexLevelParameterfv = NULL;
	replicate_spu.diff_dispatch.GetTexLevelParameteriv = NULL;
	replicate_spu.diff_dispatch.GetTexParameterfv = NULL;
	replicate_spu.diff_dispatch.GetTexParameteriv = NULL;
	replicate_spu.diff_dispatch.GetTrackMatrixivNV = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribPointervARB = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribPointervNV = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribdvARB = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribdvNV = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribfvARB = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribfvNV = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribivARB = NULL;
	replicate_spu.diff_dispatch.GetVertexAttribivNV = NULL;
	replicate_spu.diff_dispatch.Hint = (replicate_spu.swap ? crPackHintSWAP : crPackHint);
	replicate_spu.diff_dispatch.IndexMask = (replicate_spu.swap ? crPackIndexMaskSWAP : crPackIndexMask);
	replicate_spu.diff_dispatch.IndexPointer = (replicate_spu.swap ? crPackIndexPointerSWAP : crPackIndexPointer);
	replicate_spu.diff_dispatch.Indexd = (replicate_spu.swap ? crPackIndexdSWAP : crPackIndexd);
	replicate_spu.diff_dispatch.Indexdv = (replicate_spu.swap ? crPackIndexdvSWAP : crPackIndexdv);
	replicate_spu.diff_dispatch.Indexf = (replicate_spu.swap ? crPackIndexfSWAP : crPackIndexf);
	replicate_spu.diff_dispatch.Indexfv = (replicate_spu.swap ? crPackIndexfvSWAP : crPackIndexfv);
	replicate_spu.diff_dispatch.Indexi = (replicate_spu.swap ? crPackIndexiSWAP : crPackIndexi);
	replicate_spu.diff_dispatch.Indexiv = (replicate_spu.swap ? crPackIndexivSWAP : crPackIndexiv);
	replicate_spu.diff_dispatch.Indexs = (replicate_spu.swap ? crPackIndexsSWAP : crPackIndexs);
	replicate_spu.diff_dispatch.Indexsv = (replicate_spu.swap ? crPackIndexsvSWAP : crPackIndexsv);
	replicate_spu.diff_dispatch.Indexub = (replicate_spu.swap ? crPackIndexubSWAP : crPackIndexub);
	replicate_spu.diff_dispatch.Indexubv = (replicate_spu.swap ? crPackIndexubvSWAP : crPackIndexubv);
	replicate_spu.diff_dispatch.InitNames = (replicate_spu.swap ? crPackInitNamesSWAP : crPackInitNames);
	replicate_spu.diff_dispatch.InterleavedArrays = (replicate_spu.swap ? crPackInterleavedArraysSWAP : crPackInterleavedArrays);
	replicate_spu.diff_dispatch.IsBufferARB = NULL;
	replicate_spu.diff_dispatch.IsEnabled = NULL;
	replicate_spu.diff_dispatch.IsFenceNV = NULL;
	replicate_spu.diff_dispatch.IsList = NULL;
	replicate_spu.diff_dispatch.IsProgramARB = NULL;
	replicate_spu.diff_dispatch.IsQueryARB = NULL;
	replicate_spu.diff_dispatch.IsTexture = NULL;
	replicate_spu.diff_dispatch.LightModelf = (replicate_spu.swap ? crPackLightModelfSWAP : crPackLightModelf);
	replicate_spu.diff_dispatch.LightModelfv = (replicate_spu.swap ? crPackLightModelfvSWAP : crPackLightModelfv);
	replicate_spu.diff_dispatch.LightModeli = (replicate_spu.swap ? crPackLightModeliSWAP : crPackLightModeli);
	replicate_spu.diff_dispatch.LightModeliv = (replicate_spu.swap ? crPackLightModelivSWAP : crPackLightModeliv);
	replicate_spu.diff_dispatch.Lightf = (replicate_spu.swap ? crPackLightfSWAP : crPackLightf);
	replicate_spu.diff_dispatch.Lightfv = (replicate_spu.swap ? crPackLightfvSWAP : crPackLightfv);
	replicate_spu.diff_dispatch.Lighti = (replicate_spu.swap ? crPackLightiSWAP : crPackLighti);
	replicate_spu.diff_dispatch.Lightiv = (replicate_spu.swap ? crPackLightivSWAP : crPackLightiv);
	replicate_spu.diff_dispatch.LineStipple = (replicate_spu.swap ? crPackLineStippleSWAP : crPackLineStipple);
	replicate_spu.diff_dispatch.LineWidth = (replicate_spu.swap ? crPackLineWidthSWAP : crPackLineWidth);
	replicate_spu.diff_dispatch.ListBase = (replicate_spu.swap ? crPackListBaseSWAP : crPackListBase);
	replicate_spu.diff_dispatch.LoadIdentity = (replicate_spu.swap ? crPackLoadIdentitySWAP : crPackLoadIdentity);
	replicate_spu.diff_dispatch.LoadMatrixd = (replicate_spu.swap ? crPackLoadMatrixdSWAP : crPackLoadMatrixd);
	replicate_spu.diff_dispatch.LoadMatrixf = (replicate_spu.swap ? crPackLoadMatrixfSWAP : crPackLoadMatrixf);
	replicate_spu.diff_dispatch.LoadName = (replicate_spu.swap ? crPackLoadNameSWAP : crPackLoadName);
	replicate_spu.diff_dispatch.LoadProgramNV = (replicate_spu.swap ? crPackLoadProgramNVSWAP : crPackLoadProgramNV);
	replicate_spu.diff_dispatch.LoadTransposeMatrixdARB = (replicate_spu.swap ? crPackLoadTransposeMatrixdARBSWAP : crPackLoadTransposeMatrixdARB);
	replicate_spu.diff_dispatch.LoadTransposeMatrixfARB = (replicate_spu.swap ? crPackLoadTransposeMatrixfARBSWAP : crPackLoadTransposeMatrixfARB);
	replicate_spu.diff_dispatch.LogicOp = (replicate_spu.swap ? crPackLogicOpSWAP : crPackLogicOp);
	replicate_spu.diff_dispatch.MakeCurrent = (replicate_spu.swap ? crPackMakeCurrentSWAP : crPackMakeCurrent);
	replicate_spu.diff_dispatch.Map1d = (replicate_spu.swap ? crPackMap1dSWAP : crPackMap1d);
	replicate_spu.diff_dispatch.Map1f = (replicate_spu.swap ? crPackMap1fSWAP : crPackMap1f);
	replicate_spu.diff_dispatch.Map2d = (replicate_spu.swap ? crPackMap2dSWAP : crPackMap2d);
	replicate_spu.diff_dispatch.Map2f = (replicate_spu.swap ? crPackMap2fSWAP : crPackMap2f);
	replicate_spu.diff_dispatch.MapBufferARB = NULL;
	replicate_spu.diff_dispatch.MapGrid1d = (replicate_spu.swap ? crPackMapGrid1dSWAP : crPackMapGrid1d);
	replicate_spu.diff_dispatch.MapGrid1f = (replicate_spu.swap ? crPackMapGrid1fSWAP : crPackMapGrid1f);
	replicate_spu.diff_dispatch.MapGrid2d = (replicate_spu.swap ? crPackMapGrid2dSWAP : crPackMapGrid2d);
	replicate_spu.diff_dispatch.MapGrid2f = (replicate_spu.swap ? crPackMapGrid2fSWAP : crPackMapGrid2f);
	replicate_spu.diff_dispatch.Materialf = (replicate_spu.swap ? crPackMaterialfSWAP : crPackMaterialf);
	replicate_spu.diff_dispatch.Materialfv = (replicate_spu.swap ? crPackMaterialfvSWAP : crPackMaterialfv);
	replicate_spu.diff_dispatch.Materiali = (replicate_spu.swap ? crPackMaterialiSWAP : crPackMateriali);
	replicate_spu.diff_dispatch.Materialiv = (replicate_spu.swap ? crPackMaterialivSWAP : crPackMaterialiv);
	replicate_spu.diff_dispatch.MatrixMode = (replicate_spu.swap ? crPackMatrixModeSWAP : crPackMatrixMode);
	replicate_spu.diff_dispatch.MultMatrixd = (replicate_spu.swap ? crPackMultMatrixdSWAP : crPackMultMatrixd);
	replicate_spu.diff_dispatch.MultMatrixf = (replicate_spu.swap ? crPackMultMatrixfSWAP : crPackMultMatrixf);
	replicate_spu.diff_dispatch.MultTransposeMatrixdARB = (replicate_spu.swap ? crPackMultTransposeMatrixdARBSWAP : crPackMultTransposeMatrixdARB);
	replicate_spu.diff_dispatch.MultTransposeMatrixfARB = (replicate_spu.swap ? crPackMultTransposeMatrixfARBSWAP : crPackMultTransposeMatrixfARB);
	replicate_spu.diff_dispatch.MultiDrawArraysEXT = (replicate_spu.swap ? crPackMultiDrawArraysEXTSWAP : crPackMultiDrawArraysEXT);
	replicate_spu.diff_dispatch.MultiDrawElementsEXT = (replicate_spu.swap ? crPackMultiDrawElementsEXTSWAP : crPackMultiDrawElementsEXT);
	replicate_spu.diff_dispatch.MultiTexCoord1dARB = (replicate_spu.swap ? crPackMultiTexCoord1dARBSWAP : crPackMultiTexCoord1dARB);
	replicate_spu.diff_dispatch.MultiTexCoord1dvARB = (replicate_spu.swap ? crPackMultiTexCoord1dvARBSWAP : crPackMultiTexCoord1dvARB);
	replicate_spu.diff_dispatch.MultiTexCoord1fARB = (replicate_spu.swap ? crPackMultiTexCoord1fARBSWAP : crPackMultiTexCoord1fARB);
	replicate_spu.diff_dispatch.MultiTexCoord1fvARB = (replicate_spu.swap ? crPackMultiTexCoord1fvARBSWAP : crPackMultiTexCoord1fvARB);
	replicate_spu.diff_dispatch.MultiTexCoord1iARB = (replicate_spu.swap ? crPackMultiTexCoord1iARBSWAP : crPackMultiTexCoord1iARB);
	replicate_spu.diff_dispatch.MultiTexCoord1ivARB = (replicate_spu.swap ? crPackMultiTexCoord1ivARBSWAP : crPackMultiTexCoord1ivARB);
	replicate_spu.diff_dispatch.MultiTexCoord1sARB = (replicate_spu.swap ? crPackMultiTexCoord1sARBSWAP : crPackMultiTexCoord1sARB);
	replicate_spu.diff_dispatch.MultiTexCoord1svARB = (replicate_spu.swap ? crPackMultiTexCoord1svARBSWAP : crPackMultiTexCoord1svARB);
	replicate_spu.diff_dispatch.MultiTexCoord2dARB = (replicate_spu.swap ? crPackMultiTexCoord2dARBSWAP : crPackMultiTexCoord2dARB);
	replicate_spu.diff_dispatch.MultiTexCoord2dvARB = (replicate_spu.swap ? crPackMultiTexCoord2dvARBSWAP : crPackMultiTexCoord2dvARB);
	replicate_spu.diff_dispatch.MultiTexCoord2fARB = (replicate_spu.swap ? crPackMultiTexCoord2fARBSWAP : crPackMultiTexCoord2fARB);
	replicate_spu.diff_dispatch.MultiTexCoord2fvARB = (replicate_spu.swap ? crPackMultiTexCoord2fvARBSWAP : crPackMultiTexCoord2fvARB);
	replicate_spu.diff_dispatch.MultiTexCoord2iARB = (replicate_spu.swap ? crPackMultiTexCoord2iARBSWAP : crPackMultiTexCoord2iARB);
	replicate_spu.diff_dispatch.MultiTexCoord2ivARB = (replicate_spu.swap ? crPackMultiTexCoord2ivARBSWAP : crPackMultiTexCoord2ivARB);
	replicate_spu.diff_dispatch.MultiTexCoord2sARB = (replicate_spu.swap ? crPackMultiTexCoord2sARBSWAP : crPackMultiTexCoord2sARB);
	replicate_spu.diff_dispatch.MultiTexCoord2svARB = (replicate_spu.swap ? crPackMultiTexCoord2svARBSWAP : crPackMultiTexCoord2svARB);
	replicate_spu.diff_dispatch.MultiTexCoord3dARB = (replicate_spu.swap ? crPackMultiTexCoord3dARBSWAP : crPackMultiTexCoord3dARB);
	replicate_spu.diff_dispatch.MultiTexCoord3dvARB = (replicate_spu.swap ? crPackMultiTexCoord3dvARBSWAP : crPackMultiTexCoord3dvARB);
	replicate_spu.diff_dispatch.MultiTexCoord3fARB = (replicate_spu.swap ? crPackMultiTexCoord3fARBSWAP : crPackMultiTexCoord3fARB);
	replicate_spu.diff_dispatch.MultiTexCoord3fvARB = (replicate_spu.swap ? crPackMultiTexCoord3fvARBSWAP : crPackMultiTexCoord3fvARB);
	replicate_spu.diff_dispatch.MultiTexCoord3iARB = (replicate_spu.swap ? crPackMultiTexCoord3iARBSWAP : crPackMultiTexCoord3iARB);
	replicate_spu.diff_dispatch.MultiTexCoord3ivARB = (replicate_spu.swap ? crPackMultiTexCoord3ivARBSWAP : crPackMultiTexCoord3ivARB);
	replicate_spu.diff_dispatch.MultiTexCoord3sARB = (replicate_spu.swap ? crPackMultiTexCoord3sARBSWAP : crPackMultiTexCoord3sARB);
	replicate_spu.diff_dispatch.MultiTexCoord3svARB = (replicate_spu.swap ? crPackMultiTexCoord3svARBSWAP : crPackMultiTexCoord3svARB);
	replicate_spu.diff_dispatch.MultiTexCoord4dARB = (replicate_spu.swap ? crPackMultiTexCoord4dARBSWAP : crPackMultiTexCoord4dARB);
	replicate_spu.diff_dispatch.MultiTexCoord4dvARB = (replicate_spu.swap ? crPackMultiTexCoord4dvARBSWAP : crPackMultiTexCoord4dvARB);
	replicate_spu.diff_dispatch.MultiTexCoord4fARB = (replicate_spu.swap ? crPackMultiTexCoord4fARBSWAP : crPackMultiTexCoord4fARB);
	replicate_spu.diff_dispatch.MultiTexCoord4fvARB = (replicate_spu.swap ? crPackMultiTexCoord4fvARBSWAP : crPackMultiTexCoord4fvARB);
	replicate_spu.diff_dispatch.MultiTexCoord4iARB = (replicate_spu.swap ? crPackMultiTexCoord4iARBSWAP : crPackMultiTexCoord4iARB);
	replicate_spu.diff_dispatch.MultiTexCoord4ivARB = (replicate_spu.swap ? crPackMultiTexCoord4ivARBSWAP : crPackMultiTexCoord4ivARB);
	replicate_spu.diff_dispatch.MultiTexCoord4sARB = (replicate_spu.swap ? crPackMultiTexCoord4sARBSWAP : crPackMultiTexCoord4sARB);
	replicate_spu.diff_dispatch.MultiTexCoord4svARB = (replicate_spu.swap ? crPackMultiTexCoord4svARBSWAP : crPackMultiTexCoord4svARB);
	replicate_spu.diff_dispatch.NewList = (replicate_spu.swap ? crPackNewListSWAP : crPackNewList);
	replicate_spu.diff_dispatch.Normal3b = (replicate_spu.swap ? crPackNormal3bSWAP : crPackNormal3b);
	replicate_spu.diff_dispatch.Normal3bv = (replicate_spu.swap ? crPackNormal3bvSWAP : crPackNormal3bv);
	replicate_spu.diff_dispatch.Normal3d = (replicate_spu.swap ? crPackNormal3dSWAP : crPackNormal3d);
	replicate_spu.diff_dispatch.Normal3dv = (replicate_spu.swap ? crPackNormal3dvSWAP : crPackNormal3dv);
	replicate_spu.diff_dispatch.Normal3f = (replicate_spu.swap ? crPackNormal3fSWAP : crPackNormal3f);
	replicate_spu.diff_dispatch.Normal3fv = (replicate_spu.swap ? crPackNormal3fvSWAP : crPackNormal3fv);
	replicate_spu.diff_dispatch.Normal3i = (replicate_spu.swap ? crPackNormal3iSWAP : crPackNormal3i);
	replicate_spu.diff_dispatch.Normal3iv = (replicate_spu.swap ? crPackNormal3ivSWAP : crPackNormal3iv);
	replicate_spu.diff_dispatch.Normal3s = (replicate_spu.swap ? crPackNormal3sSWAP : crPackNormal3s);
	replicate_spu.diff_dispatch.Normal3sv = (replicate_spu.swap ? crPackNormal3svSWAP : crPackNormal3sv);
	replicate_spu.diff_dispatch.NormalPointer = (replicate_spu.swap ? crPackNormalPointerSWAP : crPackNormalPointer);
	replicate_spu.diff_dispatch.Ortho = (replicate_spu.swap ? crPackOrthoSWAP : crPackOrtho);
	replicate_spu.diff_dispatch.PassThrough = (replicate_spu.swap ? crPackPassThroughSWAP : crPackPassThrough);
	replicate_spu.diff_dispatch.PixelMapfv = (replicate_spu.swap ? crPackPixelMapfvSWAP : crPackPixelMapfv);
	replicate_spu.diff_dispatch.PixelMapuiv = (replicate_spu.swap ? crPackPixelMapuivSWAP : crPackPixelMapuiv);
	replicate_spu.diff_dispatch.PixelMapusv = (replicate_spu.swap ? crPackPixelMapusvSWAP : crPackPixelMapusv);
	replicate_spu.diff_dispatch.PixelStoref = (replicate_spu.swap ? crPackPixelStorefSWAP : crPackPixelStoref);
	replicate_spu.diff_dispatch.PixelStorei = (replicate_spu.swap ? crPackPixelStoreiSWAP : crPackPixelStorei);
	replicate_spu.diff_dispatch.PixelTransferf = (replicate_spu.swap ? crPackPixelTransferfSWAP : crPackPixelTransferf);
	replicate_spu.diff_dispatch.PixelTransferi = (replicate_spu.swap ? crPackPixelTransferiSWAP : crPackPixelTransferi);
	replicate_spu.diff_dispatch.PixelZoom = (replicate_spu.swap ? crPackPixelZoomSWAP : crPackPixelZoom);
	replicate_spu.diff_dispatch.PointParameterfARB = (replicate_spu.swap ? crPackPointParameterfARBSWAP : crPackPointParameterfARB);
	replicate_spu.diff_dispatch.PointParameterfvARB = (replicate_spu.swap ? crPackPointParameterfvARBSWAP : crPackPointParameterfvARB);
	replicate_spu.diff_dispatch.PointParameteri = (replicate_spu.swap ? crPackPointParameteriSWAP : crPackPointParameteri);
	replicate_spu.diff_dispatch.PointParameteriv = (replicate_spu.swap ? crPackPointParameterivSWAP : crPackPointParameteriv);
	replicate_spu.diff_dispatch.PointSize = (replicate_spu.swap ? crPackPointSizeSWAP : crPackPointSize);
	replicate_spu.diff_dispatch.PolygonMode = (replicate_spu.swap ? crPackPolygonModeSWAP : crPackPolygonMode);
	replicate_spu.diff_dispatch.PolygonOffset = (replicate_spu.swap ? crPackPolygonOffsetSWAP : crPackPolygonOffset);
	replicate_spu.diff_dispatch.PolygonStipple = (replicate_spu.swap ? crPackPolygonStippleSWAP : crPackPolygonStipple);
	replicate_spu.diff_dispatch.PopAttrib = (replicate_spu.swap ? crPackPopAttribSWAP : crPackPopAttrib);
	replicate_spu.diff_dispatch.PopClientAttrib = crStatePopClientAttrib;
	replicate_spu.diff_dispatch.PopMatrix = (replicate_spu.swap ? crPackPopMatrixSWAP : crPackPopMatrix);
	replicate_spu.diff_dispatch.PopName = (replicate_spu.swap ? crPackPopNameSWAP : crPackPopName);
	replicate_spu.diff_dispatch.PrioritizeTextures = (replicate_spu.swap ? crPackPrioritizeTexturesSWAP : crPackPrioritizeTextures);
	replicate_spu.diff_dispatch.ProgramEnvParameter4dARB = (replicate_spu.swap ? crPackProgramEnvParameter4dARBSWAP : crPackProgramEnvParameter4dARB);
	replicate_spu.diff_dispatch.ProgramEnvParameter4dvARB = (replicate_spu.swap ? crPackProgramEnvParameter4dvARBSWAP : crPackProgramEnvParameter4dvARB);
	replicate_spu.diff_dispatch.ProgramEnvParameter4fARB = (replicate_spu.swap ? crPackProgramEnvParameter4fARBSWAP : crPackProgramEnvParameter4fARB);
	replicate_spu.diff_dispatch.ProgramEnvParameter4fvARB = (replicate_spu.swap ? crPackProgramEnvParameter4fvARBSWAP : crPackProgramEnvParameter4fvARB);
	replicate_spu.diff_dispatch.ProgramLocalParameter4dARB = (replicate_spu.swap ? crPackProgramLocalParameter4dARBSWAP : crPackProgramLocalParameter4dARB);
	replicate_spu.diff_dispatch.ProgramLocalParameter4dvARB = (replicate_spu.swap ? crPackProgramLocalParameter4dvARBSWAP : crPackProgramLocalParameter4dvARB);
	replicate_spu.diff_dispatch.ProgramLocalParameter4fARB = (replicate_spu.swap ? crPackProgramLocalParameter4fARBSWAP : crPackProgramLocalParameter4fARB);
	replicate_spu.diff_dispatch.ProgramLocalParameter4fvARB = (replicate_spu.swap ? crPackProgramLocalParameter4fvARBSWAP : crPackProgramLocalParameter4fvARB);
	replicate_spu.diff_dispatch.ProgramNamedParameter4dNV = (replicate_spu.swap ? crPackProgramNamedParameter4dNVSWAP : crPackProgramNamedParameter4dNV);
	replicate_spu.diff_dispatch.ProgramNamedParameter4dvNV = (replicate_spu.swap ? crPackProgramNamedParameter4dvNVSWAP : crPackProgramNamedParameter4dvNV);
	replicate_spu.diff_dispatch.ProgramNamedParameter4fNV = (replicate_spu.swap ? crPackProgramNamedParameter4fNVSWAP : crPackProgramNamedParameter4fNV);
	replicate_spu.diff_dispatch.ProgramNamedParameter4fvNV = (replicate_spu.swap ? crPackProgramNamedParameter4fvNVSWAP : crPackProgramNamedParameter4fvNV);
	replicate_spu.diff_dispatch.ProgramParameter4dNV = (replicate_spu.swap ? crPackProgramParameter4dNVSWAP : crPackProgramParameter4dNV);
	replicate_spu.diff_dispatch.ProgramParameter4dvNV = (replicate_spu.swap ? crPackProgramParameter4dvNVSWAP : crPackProgramParameter4dvNV);
	replicate_spu.diff_dispatch.ProgramParameter4fNV = (replicate_spu.swap ? crPackProgramParameter4fNVSWAP : crPackProgramParameter4fNV);
	replicate_spu.diff_dispatch.ProgramParameter4fvNV = (replicate_spu.swap ? crPackProgramParameter4fvNVSWAP : crPackProgramParameter4fvNV);
	replicate_spu.diff_dispatch.ProgramParameters4dvNV = (replicate_spu.swap ? crPackProgramParameters4dvNVSWAP : crPackProgramParameters4dvNV);
	replicate_spu.diff_dispatch.ProgramParameters4fvNV = (replicate_spu.swap ? crPackProgramParameters4fvNVSWAP : crPackProgramParameters4fvNV);
	replicate_spu.diff_dispatch.ProgramStringARB = (replicate_spu.swap ? crPackProgramStringARBSWAP : crPackProgramStringARB);
	replicate_spu.diff_dispatch.PushAttrib = (replicate_spu.swap ? crPackPushAttribSWAP : crPackPushAttrib);
	replicate_spu.diff_dispatch.PushClientAttrib = crStatePushClientAttrib;
	replicate_spu.diff_dispatch.PushMatrix = (replicate_spu.swap ? crPackPushMatrixSWAP : crPackPushMatrix);
	replicate_spu.diff_dispatch.PushName = (replicate_spu.swap ? crPackPushNameSWAP : crPackPushName);
	replicate_spu.diff_dispatch.RasterPos2d = (replicate_spu.swap ? crPackRasterPos2dSWAP : crPackRasterPos2d);
	replicate_spu.diff_dispatch.RasterPos2dv = (replicate_spu.swap ? crPackRasterPos2dvSWAP : crPackRasterPos2dv);
	replicate_spu.diff_dispatch.RasterPos2f = (replicate_spu.swap ? crPackRasterPos2fSWAP : crPackRasterPos2f);
	replicate_spu.diff_dispatch.RasterPos2fv = (replicate_spu.swap ? crPackRasterPos2fvSWAP : crPackRasterPos2fv);
	replicate_spu.diff_dispatch.RasterPos2i = (replicate_spu.swap ? crPackRasterPos2iSWAP : crPackRasterPos2i);
	replicate_spu.diff_dispatch.RasterPos2iv = (replicate_spu.swap ? crPackRasterPos2ivSWAP : crPackRasterPos2iv);
	replicate_spu.diff_dispatch.RasterPos2s = (replicate_spu.swap ? crPackRasterPos2sSWAP : crPackRasterPos2s);
	replicate_spu.diff_dispatch.RasterPos2sv = (replicate_spu.swap ? crPackRasterPos2svSWAP : crPackRasterPos2sv);
	replicate_spu.diff_dispatch.RasterPos3d = (replicate_spu.swap ? crPackRasterPos3dSWAP : crPackRasterPos3d);
	replicate_spu.diff_dispatch.RasterPos3dv = (replicate_spu.swap ? crPackRasterPos3dvSWAP : crPackRasterPos3dv);
	replicate_spu.diff_dispatch.RasterPos3f = (replicate_spu.swap ? crPackRasterPos3fSWAP : crPackRasterPos3f);
	replicate_spu.diff_dispatch.RasterPos3fv = (replicate_spu.swap ? crPackRasterPos3fvSWAP : crPackRasterPos3fv);
	replicate_spu.diff_dispatch.RasterPos3i = (replicate_spu.swap ? crPackRasterPos3iSWAP : crPackRasterPos3i);
	replicate_spu.diff_dispatch.RasterPos3iv = (replicate_spu.swap ? crPackRasterPos3ivSWAP : crPackRasterPos3iv);
	replicate_spu.diff_dispatch.RasterPos3s = (replicate_spu.swap ? crPackRasterPos3sSWAP : crPackRasterPos3s);
	replicate_spu.diff_dispatch.RasterPos3sv = (replicate_spu.swap ? crPackRasterPos3svSWAP : crPackRasterPos3sv);
	replicate_spu.diff_dispatch.RasterPos4d = (replicate_spu.swap ? crPackRasterPos4dSWAP : crPackRasterPos4d);
	replicate_spu.diff_dispatch.RasterPos4dv = (replicate_spu.swap ? crPackRasterPos4dvSWAP : crPackRasterPos4dv);
	replicate_spu.diff_dispatch.RasterPos4f = (replicate_spu.swap ? crPackRasterPos4fSWAP : crPackRasterPos4f);
	replicate_spu.diff_dispatch.RasterPos4fv = (replicate_spu.swap ? crPackRasterPos4fvSWAP : crPackRasterPos4fv);
	replicate_spu.diff_dispatch.RasterPos4i = (replicate_spu.swap ? crPackRasterPos4iSWAP : crPackRasterPos4i);
	replicate_spu.diff_dispatch.RasterPos4iv = (replicate_spu.swap ? crPackRasterPos4ivSWAP : crPackRasterPos4iv);
	replicate_spu.diff_dispatch.RasterPos4s = (replicate_spu.swap ? crPackRasterPos4sSWAP : crPackRasterPos4s);
	replicate_spu.diff_dispatch.RasterPos4sv = (replicate_spu.swap ? crPackRasterPos4svSWAP : crPackRasterPos4sv);
	replicate_spu.diff_dispatch.ReadBuffer = (replicate_spu.swap ? crPackReadBufferSWAP : crPackReadBuffer);
	replicate_spu.diff_dispatch.ReadPixels = NULL;
	replicate_spu.diff_dispatch.Rectd = (replicate_spu.swap ? crPackRectdSWAP : crPackRectd);
	replicate_spu.diff_dispatch.Rectdv = (replicate_spu.swap ? crPackRectdvSWAP : crPackRectdv);
	replicate_spu.diff_dispatch.Rectf = (replicate_spu.swap ? crPackRectfSWAP : crPackRectf);
	replicate_spu.diff_dispatch.Rectfv = (replicate_spu.swap ? crPackRectfvSWAP : crPackRectfv);
	replicate_spu.diff_dispatch.Recti = (replicate_spu.swap ? crPackRectiSWAP : crPackRecti);
	replicate_spu.diff_dispatch.Rectiv = (replicate_spu.swap ? crPackRectivSWAP : crPackRectiv);
	replicate_spu.diff_dispatch.Rects = (replicate_spu.swap ? crPackRectsSWAP : crPackRects);
	replicate_spu.diff_dispatch.Rectsv = (replicate_spu.swap ? crPackRectsvSWAP : crPackRectsv);
	replicate_spu.diff_dispatch.RenderMode = NULL;
	replicate_spu.diff_dispatch.RequestResidentProgramsNV = (replicate_spu.swap ? crPackRequestResidentProgramsNVSWAP : crPackRequestResidentProgramsNV);
	replicate_spu.diff_dispatch.Rotated = (replicate_spu.swap ? crPackRotatedSWAP : crPackRotated);
	replicate_spu.diff_dispatch.Rotatef = (replicate_spu.swap ? crPackRotatefSWAP : crPackRotatef);
	replicate_spu.diff_dispatch.SampleCoverageARB = (replicate_spu.swap ? crPackSampleCoverageARBSWAP : crPackSampleCoverageARB);
	replicate_spu.diff_dispatch.Scaled = (replicate_spu.swap ? crPackScaledSWAP : crPackScaled);
	replicate_spu.diff_dispatch.Scalef = (replicate_spu.swap ? crPackScalefSWAP : crPackScalef);
	replicate_spu.diff_dispatch.Scissor = (replicate_spu.swap ? crPackScissorSWAP : crPackScissor);
	replicate_spu.diff_dispatch.SecondaryColor3bEXT = (replicate_spu.swap ? crPackSecondaryColor3bEXTSWAP : crPackSecondaryColor3bEXT);
	replicate_spu.diff_dispatch.SecondaryColor3bvEXT = (replicate_spu.swap ? crPackSecondaryColor3bvEXTSWAP : crPackSecondaryColor3bvEXT);
	replicate_spu.diff_dispatch.SecondaryColor3dEXT = (replicate_spu.swap ? crPackSecondaryColor3dEXTSWAP : crPackSecondaryColor3dEXT);
	replicate_spu.diff_dispatch.SecondaryColor3dvEXT = (replicate_spu.swap ? crPackSecondaryColor3dvEXTSWAP : crPackSecondaryColor3dvEXT);
	replicate_spu.diff_dispatch.SecondaryColor3fEXT = (replicate_spu.swap ? crPackSecondaryColor3fEXTSWAP : crPackSecondaryColor3fEXT);
	replicate_spu.diff_dispatch.SecondaryColor3fvEXT = (replicate_spu.swap ? crPackSecondaryColor3fvEXTSWAP : crPackSecondaryColor3fvEXT);
	replicate_spu.diff_dispatch.SecondaryColor3iEXT = (replicate_spu.swap ? crPackSecondaryColor3iEXTSWAP : crPackSecondaryColor3iEXT);
	replicate_spu.diff_dispatch.SecondaryColor3ivEXT = (replicate_spu.swap ? crPackSecondaryColor3ivEXTSWAP : crPackSecondaryColor3ivEXT);
	replicate_spu.diff_dispatch.SecondaryColor3sEXT = (replicate_spu.swap ? crPackSecondaryColor3sEXTSWAP : crPackSecondaryColor3sEXT);
	replicate_spu.diff_dispatch.SecondaryColor3svEXT = (replicate_spu.swap ? crPackSecondaryColor3svEXTSWAP : crPackSecondaryColor3svEXT);
	replicate_spu.diff_dispatch.SecondaryColor3ubEXT = (replicate_spu.swap ? crPackSecondaryColor3ubEXTSWAP : crPackSecondaryColor3ubEXT);
	replicate_spu.diff_dispatch.SecondaryColor3ubvEXT = (replicate_spu.swap ? crPackSecondaryColor3ubvEXTSWAP : crPackSecondaryColor3ubvEXT);
	replicate_spu.diff_dispatch.SecondaryColor3uiEXT = (replicate_spu.swap ? crPackSecondaryColor3uiEXTSWAP : crPackSecondaryColor3uiEXT);
	replicate_spu.diff_dispatch.SecondaryColor3uivEXT = (replicate_spu.swap ? crPackSecondaryColor3uivEXTSWAP : crPackSecondaryColor3uivEXT);
	replicate_spu.diff_dispatch.SecondaryColor3usEXT = (replicate_spu.swap ? crPackSecondaryColor3usEXTSWAP : crPackSecondaryColor3usEXT);
	replicate_spu.diff_dispatch.SecondaryColor3usvEXT = (replicate_spu.swap ? crPackSecondaryColor3usvEXTSWAP : crPackSecondaryColor3usvEXT);
	replicate_spu.diff_dispatch.SecondaryColorPointerEXT = (replicate_spu.swap ? crPackSecondaryColorPointerEXTSWAP : crPackSecondaryColorPointerEXT);
	replicate_spu.diff_dispatch.SelectBuffer = (replicate_spu.swap ? crPackSelectBufferSWAP : crPackSelectBuffer);
	replicate_spu.diff_dispatch.SemaphoreCreateCR = (replicate_spu.swap ? crPackSemaphoreCreateCRSWAP : crPackSemaphoreCreateCR);
	replicate_spu.diff_dispatch.SemaphoreDestroyCR = (replicate_spu.swap ? crPackSemaphoreDestroyCRSWAP : crPackSemaphoreDestroyCR);
	replicate_spu.diff_dispatch.SemaphorePCR = (replicate_spu.swap ? crPackSemaphorePCRSWAP : crPackSemaphorePCR);
	replicate_spu.diff_dispatch.SemaphoreVCR = (replicate_spu.swap ? crPackSemaphoreVCRSWAP : crPackSemaphoreVCR);
	replicate_spu.diff_dispatch.SetFenceNV = (replicate_spu.swap ? crPackSetFenceNVSWAP : crPackSetFenceNV);
	replicate_spu.diff_dispatch.ShadeModel = (replicate_spu.swap ? crPackShadeModelSWAP : crPackShadeModel);
	replicate_spu.diff_dispatch.StencilFunc = (replicate_spu.swap ? crPackStencilFuncSWAP : crPackStencilFunc);
	replicate_spu.diff_dispatch.StencilMask = (replicate_spu.swap ? crPackStencilMaskSWAP : crPackStencilMask);
	replicate_spu.diff_dispatch.StencilOp = (replicate_spu.swap ? crPackStencilOpSWAP : crPackStencilOp);
	replicate_spu.diff_dispatch.SwapBuffers = (replicate_spu.swap ? crPackSwapBuffersSWAP : crPackSwapBuffers);
	replicate_spu.diff_dispatch.TestFenceNV = NULL;
	replicate_spu.diff_dispatch.TexCoord1d = (replicate_spu.swap ? crPackTexCoord1dSWAP : crPackTexCoord1d);
	replicate_spu.diff_dispatch.TexCoord1dv = (replicate_spu.swap ? crPackTexCoord1dvSWAP : crPackTexCoord1dv);
	replicate_spu.diff_dispatch.TexCoord1f = (replicate_spu.swap ? crPackTexCoord1fSWAP : crPackTexCoord1f);
	replicate_spu.diff_dispatch.TexCoord1fv = (replicate_spu.swap ? crPackTexCoord1fvSWAP : crPackTexCoord1fv);
	replicate_spu.diff_dispatch.TexCoord1i = (replicate_spu.swap ? crPackTexCoord1iSWAP : crPackTexCoord1i);
	replicate_spu.diff_dispatch.TexCoord1iv = (replicate_spu.swap ? crPackTexCoord1ivSWAP : crPackTexCoord1iv);
	replicate_spu.diff_dispatch.TexCoord1s = (replicate_spu.swap ? crPackTexCoord1sSWAP : crPackTexCoord1s);
	replicate_spu.diff_dispatch.TexCoord1sv = (replicate_spu.swap ? crPackTexCoord1svSWAP : crPackTexCoord1sv);
	replicate_spu.diff_dispatch.TexCoord2d = (replicate_spu.swap ? crPackTexCoord2dSWAP : crPackTexCoord2d);
	replicate_spu.diff_dispatch.TexCoord2dv = (replicate_spu.swap ? crPackTexCoord2dvSWAP : crPackTexCoord2dv);
	replicate_spu.diff_dispatch.TexCoord2f = (replicate_spu.swap ? crPackTexCoord2fSWAP : crPackTexCoord2f);
	replicate_spu.diff_dispatch.TexCoord2fv = (replicate_spu.swap ? crPackTexCoord2fvSWAP : crPackTexCoord2fv);
	replicate_spu.diff_dispatch.TexCoord2i = (replicate_spu.swap ? crPackTexCoord2iSWAP : crPackTexCoord2i);
	replicate_spu.diff_dispatch.TexCoord2iv = (replicate_spu.swap ? crPackTexCoord2ivSWAP : crPackTexCoord2iv);
	replicate_spu.diff_dispatch.TexCoord2s = (replicate_spu.swap ? crPackTexCoord2sSWAP : crPackTexCoord2s);
	replicate_spu.diff_dispatch.TexCoord2sv = (replicate_spu.swap ? crPackTexCoord2svSWAP : crPackTexCoord2sv);
	replicate_spu.diff_dispatch.TexCoord3d = (replicate_spu.swap ? crPackTexCoord3dSWAP : crPackTexCoord3d);
	replicate_spu.diff_dispatch.TexCoord3dv = (replicate_spu.swap ? crPackTexCoord3dvSWAP : crPackTexCoord3dv);
	replicate_spu.diff_dispatch.TexCoord3f = (replicate_spu.swap ? crPackTexCoord3fSWAP : crPackTexCoord3f);
	replicate_spu.diff_dispatch.TexCoord3fv = (replicate_spu.swap ? crPackTexCoord3fvSWAP : crPackTexCoord3fv);
	replicate_spu.diff_dispatch.TexCoord3i = (replicate_spu.swap ? crPackTexCoord3iSWAP : crPackTexCoord3i);
	replicate_spu.diff_dispatch.TexCoord3iv = (replicate_spu.swap ? crPackTexCoord3ivSWAP : crPackTexCoord3iv);
	replicate_spu.diff_dispatch.TexCoord3s = (replicate_spu.swap ? crPackTexCoord3sSWAP : crPackTexCoord3s);
	replicate_spu.diff_dispatch.TexCoord3sv = (replicate_spu.swap ? crPackTexCoord3svSWAP : crPackTexCoord3sv);
	replicate_spu.diff_dispatch.TexCoord4d = (replicate_spu.swap ? crPackTexCoord4dSWAP : crPackTexCoord4d);
	replicate_spu.diff_dispatch.TexCoord4dv = (replicate_spu.swap ? crPackTexCoord4dvSWAP : crPackTexCoord4dv);
	replicate_spu.diff_dispatch.TexCoord4f = (replicate_spu.swap ? crPackTexCoord4fSWAP : crPackTexCoord4f);
	replicate_spu.diff_dispatch.TexCoord4fv = (replicate_spu.swap ? crPackTexCoord4fvSWAP : crPackTexCoord4fv);
	replicate_spu.diff_dispatch.TexCoord4i = (replicate_spu.swap ? crPackTexCoord4iSWAP : crPackTexCoord4i);
	replicate_spu.diff_dispatch.TexCoord4iv = (replicate_spu.swap ? crPackTexCoord4ivSWAP : crPackTexCoord4iv);
	replicate_spu.diff_dispatch.TexCoord4s = (replicate_spu.swap ? crPackTexCoord4sSWAP : crPackTexCoord4s);
	replicate_spu.diff_dispatch.TexCoord4sv = (replicate_spu.swap ? crPackTexCoord4svSWAP : crPackTexCoord4sv);
	replicate_spu.diff_dispatch.TexCoordPointer = (replicate_spu.swap ? crPackTexCoordPointerSWAP : crPackTexCoordPointer);
	replicate_spu.diff_dispatch.TexEnvf = (replicate_spu.swap ? crPackTexEnvfSWAP : crPackTexEnvf);
	replicate_spu.diff_dispatch.TexEnvfv = (replicate_spu.swap ? crPackTexEnvfvSWAP : crPackTexEnvfv);
	replicate_spu.diff_dispatch.TexEnvi = (replicate_spu.swap ? crPackTexEnviSWAP : crPackTexEnvi);
	replicate_spu.diff_dispatch.TexEnviv = (replicate_spu.swap ? crPackTexEnvivSWAP : crPackTexEnviv);
	replicate_spu.diff_dispatch.TexGend = (replicate_spu.swap ? crPackTexGendSWAP : crPackTexGend);
	replicate_spu.diff_dispatch.TexGendv = (replicate_spu.swap ? crPackTexGendvSWAP : crPackTexGendv);
	replicate_spu.diff_dispatch.TexGenf = (replicate_spu.swap ? crPackTexGenfSWAP : crPackTexGenf);
	replicate_spu.diff_dispatch.TexGenfv = (replicate_spu.swap ? crPackTexGenfvSWAP : crPackTexGenfv);
	replicate_spu.diff_dispatch.TexGeni = (replicate_spu.swap ? crPackTexGeniSWAP : crPackTexGeni);
	replicate_spu.diff_dispatch.TexGeniv = (replicate_spu.swap ? crPackTexGenivSWAP : crPackTexGeniv);
	replicate_spu.diff_dispatch.TexImage1D = replicatespu_DiffTexImage1D;
	replicate_spu.diff_dispatch.TexImage2D = replicatespu_DiffTexImage2D;
	replicate_spu.diff_dispatch.TexImage3D = replicatespu_DiffTexImage3D;
	replicate_spu.diff_dispatch.TexImage3DEXT = replicatespu_DiffTexImage3DEXT;
	replicate_spu.diff_dispatch.TexParameterf = (replicate_spu.swap ? crPackTexParameterfSWAP : crPackTexParameterf);
	replicate_spu.diff_dispatch.TexParameterfv = (replicate_spu.swap ? crPackTexParameterfvSWAP : crPackTexParameterfv);
	replicate_spu.diff_dispatch.TexParameteri = (replicate_spu.swap ? crPackTexParameteriSWAP : crPackTexParameteri);
	replicate_spu.diff_dispatch.TexParameteriv = (replicate_spu.swap ? crPackTexParameterivSWAP : crPackTexParameteriv);
	replicate_spu.diff_dispatch.TexSubImage1D = replicatespu_DiffTexSubImage1D;
	replicate_spu.diff_dispatch.TexSubImage2D = replicatespu_DiffTexSubImage2D;
	replicate_spu.diff_dispatch.TexSubImage3D = replicatespu_DiffTexSubImage3D;
	replicate_spu.diff_dispatch.TrackMatrixNV = (replicate_spu.swap ? crPackTrackMatrixNVSWAP : crPackTrackMatrixNV);
	replicate_spu.diff_dispatch.Translated = (replicate_spu.swap ? crPackTranslatedSWAP : crPackTranslated);
	replicate_spu.diff_dispatch.Translatef = (replicate_spu.swap ? crPackTranslatefSWAP : crPackTranslatef);
	replicate_spu.diff_dispatch.UnmapBufferARB = NULL;
	replicate_spu.diff_dispatch.Vertex2d = (replicate_spu.swap ? crPackVertex2dSWAP : crPackVertex2d);
	replicate_spu.diff_dispatch.Vertex2dv = (replicate_spu.swap ? crPackVertex2dvSWAP : crPackVertex2dv);
	replicate_spu.diff_dispatch.Vertex2f = (replicate_spu.swap ? crPackVertex2fSWAP : crPackVertex2f);
	replicate_spu.diff_dispatch.Vertex2fv = (replicate_spu.swap ? crPackVertex2fvSWAP : crPackVertex2fv);
	replicate_spu.diff_dispatch.Vertex2i = (replicate_spu.swap ? crPackVertex2iSWAP : crPackVertex2i);
	replicate_spu.diff_dispatch.Vertex2iv = (replicate_spu.swap ? crPackVertex2ivSWAP : crPackVertex2iv);
	replicate_spu.diff_dispatch.Vertex2s = (replicate_spu.swap ? crPackVertex2sSWAP : crPackVertex2s);
	replicate_spu.diff_dispatch.Vertex2sv = (replicate_spu.swap ? crPackVertex2svSWAP : crPackVertex2sv);
	replicate_spu.diff_dispatch.Vertex3d = (replicate_spu.swap ? crPackVertex3dSWAP : crPackVertex3d);
	replicate_spu.diff_dispatch.Vertex3dv = (replicate_spu.swap ? crPackVertex3dvSWAP : crPackVertex3dv);
	replicate_spu.diff_dispatch.Vertex3f = (replicate_spu.swap ? crPackVertex3fSWAP : crPackVertex3f);
	replicate_spu.diff_dispatch.Vertex3fv = (replicate_spu.swap ? crPackVertex3fvSWAP : crPackVertex3fv);
	replicate_spu.diff_dispatch.Vertex3i = (replicate_spu.swap ? crPackVertex3iSWAP : crPackVertex3i);
	replicate_spu.diff_dispatch.Vertex3iv = (replicate_spu.swap ? crPackVertex3ivSWAP : crPackVertex3iv);
	replicate_spu.diff_dispatch.Vertex3s = (replicate_spu.swap ? crPackVertex3sSWAP : crPackVertex3s);
	replicate_spu.diff_dispatch.Vertex3sv = (replicate_spu.swap ? crPackVertex3svSWAP : crPackVertex3sv);
	replicate_spu.diff_dispatch.Vertex4d = (replicate_spu.swap ? crPackVertex4dSWAP : crPackVertex4d);
	replicate_spu.diff_dispatch.Vertex4dv = (replicate_spu.swap ? crPackVertex4dvSWAP : crPackVertex4dv);
	replicate_spu.diff_dispatch.Vertex4f = (replicate_spu.swap ? crPackVertex4fSWAP : crPackVertex4f);
	replicate_spu.diff_dispatch.Vertex4fv = (replicate_spu.swap ? crPackVertex4fvSWAP : crPackVertex4fv);
	replicate_spu.diff_dispatch.Vertex4i = (replicate_spu.swap ? crPackVertex4iSWAP : crPackVertex4i);
	replicate_spu.diff_dispatch.Vertex4iv = (replicate_spu.swap ? crPackVertex4ivSWAP : crPackVertex4iv);
	replicate_spu.diff_dispatch.Vertex4s = (replicate_spu.swap ? crPackVertex4sSWAP : crPackVertex4s);
	replicate_spu.diff_dispatch.Vertex4sv = (replicate_spu.swap ? crPackVertex4svSWAP : crPackVertex4sv);
	replicate_spu.diff_dispatch.VertexArrayRangeNV = (replicate_spu.swap ? crPackVertexArrayRangeNVSWAP : crPackVertexArrayRangeNV);
	replicate_spu.diff_dispatch.VertexAttrib1dARB = (replicate_spu.swap ? crPackVertexAttrib1dARBSWAP : crPackVertexAttrib1dARB);
	replicate_spu.diff_dispatch.VertexAttrib1dvARB = (replicate_spu.swap ? crPackVertexAttrib1dvARBSWAP : crPackVertexAttrib1dvARB);
	replicate_spu.diff_dispatch.VertexAttrib1fARB = (replicate_spu.swap ? crPackVertexAttrib1fARBSWAP : crPackVertexAttrib1fARB);
	replicate_spu.diff_dispatch.VertexAttrib1fvARB = (replicate_spu.swap ? crPackVertexAttrib1fvARBSWAP : crPackVertexAttrib1fvARB);
	replicate_spu.diff_dispatch.VertexAttrib1sARB = (replicate_spu.swap ? crPackVertexAttrib1sARBSWAP : crPackVertexAttrib1sARB);
	replicate_spu.diff_dispatch.VertexAttrib1svARB = (replicate_spu.swap ? crPackVertexAttrib1svARBSWAP : crPackVertexAttrib1svARB);
	replicate_spu.diff_dispatch.VertexAttrib2dARB = (replicate_spu.swap ? crPackVertexAttrib2dARBSWAP : crPackVertexAttrib2dARB);
	replicate_spu.diff_dispatch.VertexAttrib2dvARB = (replicate_spu.swap ? crPackVertexAttrib2dvARBSWAP : crPackVertexAttrib2dvARB);
	replicate_spu.diff_dispatch.VertexAttrib2fARB = (replicate_spu.swap ? crPackVertexAttrib2fARBSWAP : crPackVertexAttrib2fARB);
	replicate_spu.diff_dispatch.VertexAttrib2fvARB = (replicate_spu.swap ? crPackVertexAttrib2fvARBSWAP : crPackVertexAttrib2fvARB);
	replicate_spu.diff_dispatch.VertexAttrib2sARB = (replicate_spu.swap ? crPackVertexAttrib2sARBSWAP : crPackVertexAttrib2sARB);
	replicate_spu.diff_dispatch.VertexAttrib2svARB = (replicate_spu.swap ? crPackVertexAttrib2svARBSWAP : crPackVertexAttrib2svARB);
	replicate_spu.diff_dispatch.VertexAttrib3dARB = (replicate_spu.swap ? crPackVertexAttrib3dARBSWAP : crPackVertexAttrib3dARB);
	replicate_spu.diff_dispatch.VertexAttrib3dvARB = (replicate_spu.swap ? crPackVertexAttrib3dvARBSWAP : crPackVertexAttrib3dvARB);
	replicate_spu.diff_dispatch.VertexAttrib3fARB = (replicate_spu.swap ? crPackVertexAttrib3fARBSWAP : crPackVertexAttrib3fARB);
	replicate_spu.diff_dispatch.VertexAttrib3fvARB = (replicate_spu.swap ? crPackVertexAttrib3fvARBSWAP : crPackVertexAttrib3fvARB);
	replicate_spu.diff_dispatch.VertexAttrib3sARB = (replicate_spu.swap ? crPackVertexAttrib3sARBSWAP : crPackVertexAttrib3sARB);
	replicate_spu.diff_dispatch.VertexAttrib3svARB = (replicate_spu.swap ? crPackVertexAttrib3svARBSWAP : crPackVertexAttrib3svARB);
	replicate_spu.diff_dispatch.VertexAttrib4NbvARB = (replicate_spu.swap ? crPackVertexAttrib4NbvARBSWAP : crPackVertexAttrib4NbvARB);
	replicate_spu.diff_dispatch.VertexAttrib4NivARB = (replicate_spu.swap ? crPackVertexAttrib4NivARBSWAP : crPackVertexAttrib4NivARB);
	replicate_spu.diff_dispatch.VertexAttrib4NsvARB = (replicate_spu.swap ? crPackVertexAttrib4NsvARBSWAP : crPackVertexAttrib4NsvARB);
	replicate_spu.diff_dispatch.VertexAttrib4NubARB = (replicate_spu.swap ? crPackVertexAttrib4NubARBSWAP : crPackVertexAttrib4NubARB);
	replicate_spu.diff_dispatch.VertexAttrib4NubvARB = (replicate_spu.swap ? crPackVertexAttrib4NubvARBSWAP : crPackVertexAttrib4NubvARB);
	replicate_spu.diff_dispatch.VertexAttrib4NuivARB = (replicate_spu.swap ? crPackVertexAttrib4NuivARBSWAP : crPackVertexAttrib4NuivARB);
	replicate_spu.diff_dispatch.VertexAttrib4NusvARB = (replicate_spu.swap ? crPackVertexAttrib4NusvARBSWAP : crPackVertexAttrib4NusvARB);
	replicate_spu.diff_dispatch.VertexAttrib4bvARB = (replicate_spu.swap ? crPackVertexAttrib4bvARBSWAP : crPackVertexAttrib4bvARB);
	replicate_spu.diff_dispatch.VertexAttrib4dARB = (replicate_spu.swap ? crPackVertexAttrib4dARBSWAP : crPackVertexAttrib4dARB);
	replicate_spu.diff_dispatch.VertexAttrib4dvARB = (replicate_spu.swap ? crPackVertexAttrib4dvARBSWAP : crPackVertexAttrib4dvARB);
	replicate_spu.diff_dispatch.VertexAttrib4fARB = (replicate_spu.swap ? crPackVertexAttrib4fARBSWAP : crPackVertexAttrib4fARB);
	replicate_spu.diff_dispatch.VertexAttrib4fvARB = (replicate_spu.swap ? crPackVertexAttrib4fvARBSWAP : crPackVertexAttrib4fvARB);
	replicate_spu.diff_dispatch.VertexAttrib4ivARB = (replicate_spu.swap ? crPackVertexAttrib4ivARBSWAP : crPackVertexAttrib4ivARB);
	replicate_spu.diff_dispatch.VertexAttrib4sARB = (replicate_spu.swap ? crPackVertexAttrib4sARBSWAP : crPackVertexAttrib4sARB);
	replicate_spu.diff_dispatch.VertexAttrib4svARB = (replicate_spu.swap ? crPackVertexAttrib4svARBSWAP : crPackVertexAttrib4svARB);
	replicate_spu.diff_dispatch.VertexAttrib4ubvARB = (replicate_spu.swap ? crPackVertexAttrib4ubvARBSWAP : crPackVertexAttrib4ubvARB);
	replicate_spu.diff_dispatch.VertexAttrib4uivARB = (replicate_spu.swap ? crPackVertexAttrib4uivARBSWAP : crPackVertexAttrib4uivARB);
	replicate_spu.diff_dispatch.VertexAttrib4usvARB = (replicate_spu.swap ? crPackVertexAttrib4usvARBSWAP : crPackVertexAttrib4usvARB);
	replicate_spu.diff_dispatch.VertexAttribPointerARB = (replicate_spu.swap ? crPackVertexAttribPointerARBSWAP : crPackVertexAttribPointerARB);
	replicate_spu.diff_dispatch.VertexAttribPointerNV = (replicate_spu.swap ? crPackVertexAttribPointerNVSWAP : crPackVertexAttribPointerNV);
	replicate_spu.diff_dispatch.VertexAttribs1dvNV = (replicate_spu.swap ? crPackVertexAttribs1dvNVSWAP : crPackVertexAttribs1dvNV);
	replicate_spu.diff_dispatch.VertexAttribs1fvNV = (replicate_spu.swap ? crPackVertexAttribs1fvNVSWAP : crPackVertexAttribs1fvNV);
	replicate_spu.diff_dispatch.VertexAttribs1svNV = (replicate_spu.swap ? crPackVertexAttribs1svNVSWAP : crPackVertexAttribs1svNV);
	replicate_spu.diff_dispatch.VertexAttribs2dvNV = (replicate_spu.swap ? crPackVertexAttribs2dvNVSWAP : crPackVertexAttribs2dvNV);
	replicate_spu.diff_dispatch.VertexAttribs2fvNV = (replicate_spu.swap ? crPackVertexAttribs2fvNVSWAP : crPackVertexAttribs2fvNV);
	replicate_spu.diff_dispatch.VertexAttribs2svNV = (replicate_spu.swap ? crPackVertexAttribs2svNVSWAP : crPackVertexAttribs2svNV);
	replicate_spu.diff_dispatch.VertexAttribs3dvNV = (replicate_spu.swap ? crPackVertexAttribs3dvNVSWAP : crPackVertexAttribs3dvNV);
	replicate_spu.diff_dispatch.VertexAttribs3fvNV = (replicate_spu.swap ? crPackVertexAttribs3fvNVSWAP : crPackVertexAttribs3fvNV);
	replicate_spu.diff_dispatch.VertexAttribs3svNV = (replicate_spu.swap ? crPackVertexAttribs3svNVSWAP : crPackVertexAttribs3svNV);
	replicate_spu.diff_dispatch.VertexAttribs4dvNV = (replicate_spu.swap ? crPackVertexAttribs4dvNVSWAP : crPackVertexAttribs4dvNV);
	replicate_spu.diff_dispatch.VertexAttribs4fvNV = (replicate_spu.swap ? crPackVertexAttribs4fvNVSWAP : crPackVertexAttribs4fvNV);
	replicate_spu.diff_dispatch.VertexAttribs4svNV = (replicate_spu.swap ? crPackVertexAttribs4svNVSWAP : crPackVertexAttribs4svNV);
	replicate_spu.diff_dispatch.VertexAttribs4ubvNV = (replicate_spu.swap ? crPackVertexAttribs4ubvNVSWAP : crPackVertexAttribs4ubvNV);
	replicate_spu.diff_dispatch.VertexPointer = (replicate_spu.swap ? crPackVertexPointerSWAP : crPackVertexPointer);
	replicate_spu.diff_dispatch.Viewport = (replicate_spu.swap ? crPackViewportSWAP : crPackViewport);
	replicate_spu.diff_dispatch.WindowCreate = NULL;
	replicate_spu.diff_dispatch.WindowDestroy = (replicate_spu.swap ? crPackWindowDestroySWAP : crPackWindowDestroy);
	replicate_spu.diff_dispatch.WindowPos2dARB = (replicate_spu.swap ? crPackWindowPos2dARBSWAP : crPackWindowPos2dARB);
	replicate_spu.diff_dispatch.WindowPos2dvARB = (replicate_spu.swap ? crPackWindowPos2dvARBSWAP : crPackWindowPos2dvARB);
	replicate_spu.diff_dispatch.WindowPos2fARB = (replicate_spu.swap ? crPackWindowPos2fARBSWAP : crPackWindowPos2fARB);
	replicate_spu.diff_dispatch.WindowPos2fvARB = (replicate_spu.swap ? crPackWindowPos2fvARBSWAP : crPackWindowPos2fvARB);
	replicate_spu.diff_dispatch.WindowPos2iARB = (replicate_spu.swap ? crPackWindowPos2iARBSWAP : crPackWindowPos2iARB);
	replicate_spu.diff_dispatch.WindowPos2ivARB = (replicate_spu.swap ? crPackWindowPos2ivARBSWAP : crPackWindowPos2ivARB);
	replicate_spu.diff_dispatch.WindowPos2sARB = (replicate_spu.swap ? crPackWindowPos2sARBSWAP : crPackWindowPos2sARB);
	replicate_spu.diff_dispatch.WindowPos2svARB = (replicate_spu.swap ? crPackWindowPos2svARBSWAP : crPackWindowPos2svARB);
	replicate_spu.diff_dispatch.WindowPos3dARB = (replicate_spu.swap ? crPackWindowPos3dARBSWAP : crPackWindowPos3dARB);
	replicate_spu.diff_dispatch.WindowPos3dvARB = (replicate_spu.swap ? crPackWindowPos3dvARBSWAP : crPackWindowPos3dvARB);
	replicate_spu.diff_dispatch.WindowPos3fARB = (replicate_spu.swap ? crPackWindowPos3fARBSWAP : crPackWindowPos3fARB);
	replicate_spu.diff_dispatch.WindowPos3fvARB = (replicate_spu.swap ? crPackWindowPos3fvARBSWAP : crPackWindowPos3fvARB);
	replicate_spu.diff_dispatch.WindowPos3iARB = (replicate_spu.swap ? crPackWindowPos3iARBSWAP : crPackWindowPos3iARB);
	replicate_spu.diff_dispatch.WindowPos3ivARB = (replicate_spu.swap ? crPackWindowPos3ivARBSWAP : crPackWindowPos3ivARB);
	replicate_spu.diff_dispatch.WindowPos3sARB = (replicate_spu.swap ? crPackWindowPos3sARBSWAP : crPackWindowPos3sARB);
	replicate_spu.diff_dispatch.WindowPos3svARB = (replicate_spu.swap ? crPackWindowPos3svARBSWAP : crPackWindowPos3svARB);
	replicate_spu.diff_dispatch.WindowPosition = (replicate_spu.swap ? crPackWindowPositionSWAP : crPackWindowPosition);
	replicate_spu.diff_dispatch.WindowShow = (replicate_spu.swap ? crPackWindowShowSWAP : crPackWindowShow);
	replicate_spu.diff_dispatch.WindowSize = (replicate_spu.swap ? crPackWindowSizeSWAP : crPackWindowSize);
	replicate_spu.diff_dispatch.Writeback = (replicate_spu.swap ? crPackWritebackSWAP : crPackWriteback);
	replicate_spu.diff_dispatch.ZPixCR = replicatespu_DiffZPixCR;
	crStateDiffAPI( &replicate_spu.diff_dispatch );
}
