/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - AUTOMATICALLY GENERATED BY replicatespu_beginend.py */
#include "replicatespu.h"
#include "cr_packfunctions.h"
#include "replicatespu_proto.h"

void REPLICATESPU_APIENTRY replicatespu_Begin( GLenum mode )
{
	GET_THREAD(thread);
	CRPackBuffer *buf = &thread->BeginEndBuffer;

	CRASSERT( mode >= GL_POINTS && mode <= GL_POLYGON );

	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileBegin(mode);
	}
	if (replicate_spu.swap)
	{
		crPackBeginSWAP( mode );
	}
	else
	{
		crPackBegin( mode );
	}

	if ( thread->server.conn->Barf ) {
		thread->BeginEndMode = mode;
		thread->BeginEndState = -1;
		if ( mode == GL_LINES || mode == GL_TRIANGLES || mode == GL_QUADS || mode == GL_POLYGON )
		{
			CRASSERT(!buf->pack);

			crPackReleaseBuffer( thread->packer );
			buf->pack = crNetAlloc( thread->server.conn );
			crPackInitBuffer( buf, buf->pack, thread->server.conn->buffer_size, thread->server.conn->mtu );
			buf->holds_BeginEnd = 1;
			buf->in_BeginEnd = 1;
			crPackSetBuffer( thread->packer, buf );

			thread->BeginEndState = 0;
		}
	}
}

void REPLICATESPU_APIENTRY replicatespu_End( void )
{
	GET_THREAD(thread);
	CRPackBuffer *buf = &thread->BeginEndBuffer;

	if ( thread->server.conn->Barf &&
		(thread->BeginEndMode == GL_LINES
		|| thread->BeginEndMode == GL_TRIANGLES
		|| thread->BeginEndMode == GL_QUADS
		|| thread->BeginEndMode == GL_POLYGON ) )
	{
		CRASSERT(buf->pack);

		crPackReleaseBuffer( thread->packer );
		crPackSetBuffer( thread->packer, &thread->normBuffer );
		if ( !crPackCanHoldBuffer( buf ) )
			replicatespuFlush( (void *) thread );

		crPackAppendBuffer( buf );
		crNetFree( thread->server.conn, buf->pack );
		buf->pack = NULL;
	}

	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileEnd();
	}
	if (replicate_spu.swap)
	{
		crPackEndSWAP();
	}
	else
	{
		crPackEnd();
	}
}

static void DoVertex( void )
{
	GET_THREAD(thread);
	CRPackBuffer *buf = &thread->BeginEndBuffer;
	CRPackBuffer *gbuf = &thread->normBuffer;
	int num_data;
	int num_opcode;

	/*crDebug( "really doing Vertex" );*/
	crPackReleaseBuffer( thread->packer );
	num_data = buf->data_current - buf->data_start;
	num_opcode = buf->opcode_start - buf->opcode_current;
	crPackSetBuffer( thread->packer, gbuf );
	if ( !crPackCanHoldBuffer( buf ) )
		/* doesn't hold, first flush gbuf*/
		replicatespuFlush( (void *) thread );

	crPackAppendBuffer( buf );
	crPackReleaseBuffer( thread->packer );
	crPackSetBuffer( thread->packer, buf );
	crPackResetPointers(thread->packer);
}

static void RunState( void )
{
	GET_THREAD(thread);
	if (! thread->server.conn->Barf ) return;
	if (thread->BeginEndState == -1) return;
	switch(thread->BeginEndMode) {
	case GL_POLYGON:
		return;
	case GL_LINES:
		if ((thread->BeginEndState + 1) % 2)
		{
			thread->BeginEndState = (thread->BeginEndState + 1) % 2;
			return;
		}
		break;
	case GL_TRIANGLES:
		if ((thread->BeginEndState + 1) % 3)
		{
			thread->BeginEndState = (thread->BeginEndState + 1) % 3;
			return;
		}
		break;
	case GL_QUADS:
		if ((thread->BeginEndState + 1) % 4)
		{
			thread->BeginEndState = (thread->BeginEndState + 1) % 4;
			return;
		}
		break;
	}
	DoVertex();
}

void REPLICATESPU_APIENTRY replicatespu_Vertex2d( GLdouble x, GLdouble y )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2d(x, y);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2dSWAP( x, y );
	}
	else
	{
		crPackVertex2d( x, y );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2dv( const GLdouble * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2dv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2dvSWAP( v );
	}
	else
	{
		crPackVertex2dv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2f( GLfloat x, GLfloat y )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2f(x, y);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2fSWAP( x, y );
	}
	else
	{
		crPackVertex2f( x, y );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2fv( const GLfloat * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2fv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2fvSWAP( v );
	}
	else
	{
		crPackVertex2fv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2i( GLint x, GLint y )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2i(x, y);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2iSWAP( x, y );
	}
	else
	{
		crPackVertex2i( x, y );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2iv( const GLint * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2iv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2ivSWAP( v );
	}
	else
	{
		crPackVertex2iv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2s( GLshort x, GLshort y )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2s(x, y);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2sSWAP( x, y );
	}
	else
	{
		crPackVertex2s( x, y );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex2sv( const GLshort * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex2sv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex2svSWAP( v );
	}
	else
	{
		crPackVertex2sv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3d( GLdouble x, GLdouble y, GLdouble z )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3d(x, y, z);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3dSWAP( x, y, z );
	}
	else
	{
		crPackVertex3d( x, y, z );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3dv( const GLdouble * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3dv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3dvSWAP( v );
	}
	else
	{
		crPackVertex3dv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3f( GLfloat x, GLfloat y, GLfloat z )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3f(x, y, z);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3fSWAP( x, y, z );
	}
	else
	{
		crPackVertex3f( x, y, z );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3fv( const GLfloat * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3fv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3fvSWAP( v );
	}
	else
	{
		crPackVertex3fv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3i( GLint x, GLint y, GLint z )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3i(x, y, z);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3iSWAP( x, y, z );
	}
	else
	{
		crPackVertex3i( x, y, z );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3iv( const GLint * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3iv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3ivSWAP( v );
	}
	else
	{
		crPackVertex3iv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3s( GLshort x, GLshort y, GLshort z )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3s(x, y, z);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3sSWAP( x, y, z );
	}
	else
	{
		crPackVertex3s( x, y, z );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex3sv( const GLshort * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex3sv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex3svSWAP( v );
	}
	else
	{
		crPackVertex3sv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4d(x, y, z, w);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4dSWAP( x, y, z, w );
	}
	else
	{
		crPackVertex4d( x, y, z, w );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4dv( const GLdouble * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4dv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4dvSWAP( v );
	}
	else
	{
		crPackVertex4dv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4f(x, y, z, w);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4fSWAP( x, y, z, w );
	}
	else
	{
		crPackVertex4f( x, y, z, w );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4fv( const GLfloat * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4fv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4fvSWAP( v );
	}
	else
	{
		crPackVertex4fv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4i( GLint x, GLint y, GLint z, GLint w )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4i(x, y, z, w);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4iSWAP( x, y, z, w );
	}
	else
	{
		crPackVertex4i( x, y, z, w );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4iv( const GLint * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4iv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4ivSWAP( v );
	}
	else
	{
		crPackVertex4iv( v );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4s( GLshort x, GLshort y, GLshort z, GLshort w )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4s(x, y, z, w);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4sSWAP( x, y, z, w );
	}
	else
	{
		crPackVertex4s( x, y, z, w );
	}
	RunState();
}
void REPLICATESPU_APIENTRY replicatespu_Vertex4sv( const GLshort * v )
{
	GET_THREAD(thread);
	if (thread->currentContext->displayListMode != GL_FALSE) {
		crDLMCompileVertex4sv(v);
	}
	if (replicate_spu.swap)
	{
		crPackVertex4svSWAP( v );
	}
	else
	{
		crPackVertex4sv( v );
	}
	RunState();
}
